#include "dreamavatar_native.h"
#include "wow112_offsets.h"
#include <windows.h>

namespace TysDreamAvatar {
namespace {
constexpr unsigned long DESC_PTR_OFF=0x110UL;
constexpr unsigned long VIRTUAL_ITEM_OFF=0x007CUL;
constexpr unsigned long DISPLAY_OFF=0x01F4UL;
constexpr unsigned long NATIVE_DISPLAY_OFF=0x01F8UL;
constexpr unsigned long MOUNT_OFF=0x01FCUL;
constexpr unsigned long PLAYER_VISIBLE_ITEM1_OFF=0x03F8UL;
constexpr unsigned long VISIBLE_STRIDE=0x30UL;
constexpr unsigned VISIBLE_WORDS=8;
constexpr unsigned ENCHANT_COUNT=7;
constexpr unsigned long UPDATE_DISPLAY=0x0060ABE0UL;
constexpr unsigned long REFRESH_MOUNT=0x005FFA50UL;
constexpr unsigned long SFILE_OPEN=0x006477A0UL;
constexpr unsigned long SFILE_READ=0x00648460UL;
constexpr unsigned long SFILE_CLOSE=0x00648730UL;
constexpr unsigned long UNIT_GUID_FN=0x00515970UL;
constexpr unsigned long MAX_ID=1000000UL;
constexpr unsigned long EQUIP_TEMP_DISPLAY=15435UL;
constexpr unsigned long EQUIP_FALLBACK_DISPLAY=49UL;
constexpr unsigned long UNIT_MODEL_PTR_OFF=0x00D8UL;
constexpr unsigned long UNIT_DISPLAY_CACHE_OFF=0x0B34UL;
constexpr unsigned REMOTE_LIMIT=40;
constexpr unsigned REPLAY_LIMIT=40;
constexpr unsigned SENDER_LIMIT=40;
constexpr unsigned long PACKET_LIFETIME=300UL;
constexpr unsigned char DA_PACKET_VERSION=0xD1;
constexpr unsigned short DA_ALLOWED_FLAGS=0x007F;
constexpr unsigned long long KEY0=0x89A1F357C42D6B0EULL;
constexpr unsigned long long KEY1=0x6D27B4E98350CA71ULL;
constexpr unsigned long long DA_DOMAIN=0x445245414D415631ULL;
constexpr char B64[]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
constexpr unsigned short SYNC_CHARACTER=1u<<0;
constexpr unsigned short SYNC_WMAIN=1u<<1;
constexpr unsigned short SYNC_WOFF=1u<<2;
constexpr unsigned short SYNC_WRANGED=1u<<3;
constexpr unsigned short SYNC_GMAIN=1u<<4;
constexpr unsigned short SYNC_GOFF=1u<<5;
constexpr unsigned short SYNC_MOUNT=1u<<6;
constexpr int WEAPON_SLOT[3]={16,17,18};
constexpr int GLOW_SLOT[2]={16,17};

struct CharacterState{unsigned long original=0,nativeOriginal=0,requested=0;bool captured=false,applied=false,autoMaintain=false;};
struct WeaponState{unsigned long original[3]={0,0,0},requested[3]={0,0,0};bool captured[3]={false,false,false},applied[3]={false,false,false};bool autoMaintain=false;};
struct GlowState{unsigned long original[2][ENCHANT_COUNT]={{0}};unsigned long requested[2]={0,0};bool captured[2]={false,false},applied[2]={false,false};bool autoMaintain=false;};
struct MountState{unsigned long original=0,requested=0;bool captured=false,applied=false,autoMaintain=false;};
struct State{unsigned long long playerGuid=0;CharacterState character;WeaponState weapons;GlowState glows;MountState mount;char last[96]="NOT_INITIALIZED";};
struct Snapshot{unsigned short flags=0;unsigned long character=0,wmain=0,woff=0,wranged=0,gmain=0,goff=0,mount=0;};
struct RemoteState{bool active=false,captured=false;unsigned long long guid=0;unsigned long originalDisplay=0,originalWeapons[3]={0,0,0},originalGlows[2][ENCHANT_COUNT]={{0}},originalMount=0;Snapshot snap;};
struct SenderSnapshot{bool active=false;char sender[64]={0};Snapshot snap;};
struct Replay{bool active=false;unsigned long sender=0,issued=0,nonce=0,touched=0;unsigned long long sig=0;};
struct Buf{unsigned char d[96];unsigned n=0;};
struct ItemDbHeader{char magic[4];unsigned long recordCount,fieldCount,recordSize,stringBlockSize;};

State g={};
RemoteState remotes[REMOTE_LIMIT]={};
SenderSnapshot senders[SENDER_LIMIT]={};
Replay replay[REPLAY_LIMIT]={};
unsigned long nonceCounter=0;
Lua50::CFunction trustedGuild=0;
char runtimeStatus[96]="READY";

static void cpy(char*d,unsigned cap,const char*s){if(!d||!cap)return;unsigned i=0;if(s)for(;s[i]&&i+1<cap;++i)d[i]=s[i];d[i]=0;}
static unsigned slen(const char*s){unsigned n=0;if(s)while(s[n])++n;return n;}
static bool eqI(const char*a,const char*b){if(!a||!b)return false;for(;;++a,++b){char x=*a,y=*b;if(x>='A'&&x<='Z')x+=32;if(y>='A'&&y<='Z')y+=32;if(x!=y)return false;if(!x)return true;}}
static bool startsI(const char*s,const char*p){if(!s||!p)return false;while(*p){char a=*s++,b=*p++;if(a>='A'&&a<='Z')a+=32;if(b>='A'&&b<='Z')b+=32;if(a!=b)return false;}return true;}
static const char* suffix(const char*cmd){if(startsI(cmd,"MoonMarker.DreamAvatar."))return cmd+23;if(startsI(cmd,"DreamAvatar."))return cmd+12;return 0;}
static const char* sharedSyncSuffix(const char*cmd){
    const char*s=0;
    if(startsI(cmd,"MoonMarker.DreamAvatar."))s=cmd+23;
    else if(startsI(cmd,"DreamAvatar."))s=cmd+12;
    else if(startsI(cmd,"MoonMarker.DreamWeapon."))s=cmd+23;
    else if(startsI(cmd,"DreamWeapon."))s=cmd+12;
    return s&&startsI(s,"Sync.")?s:0;
}
static bool isSync(const char*cmd){return sharedSyncSuffix(cmd)!=0;}
static void setCode(const char*s){cpy(g.last,sizeof(g.last),s);}
static bool readable(const void*p,unsigned n,bool write){if(!p||!n)return false;MEMORY_BASIC_INFORMATION m={};if(VirtualQuery(p,&m,sizeof(m))!=sizeof(m)||m.State!=MEM_COMMIT||(m.Protect&(PAGE_GUARD|PAGE_NOACCESS)))return false;DWORD q=m.Protect&0xff;bool r=q==PAGE_READONLY||q==PAGE_READWRITE||q==PAGE_WRITECOPY||q==PAGE_EXECUTE_READ||q==PAGE_EXECUTE_READWRITE||q==PAGE_EXECUTE_WRITECOPY;bool w=q==PAGE_READWRITE||q==PAGE_WRITECOPY||q==PAGE_EXECUTE_READWRITE||q==PAGE_EXECUTE_WRITECOPY;if(!r||(write&&!w))return false;unsigned long a=(unsigned long)p,b=(unsigned long)m.BaseAddress+(unsigned long)m.RegionSize;return a+n>=a&&a+n<=b;}
static bool executable(unsigned long a){MEMORY_BASIC_INFORMATION m={};if(!a||VirtualQuery((void*)a,&m,sizeof(m))!=sizeof(m)||m.State!=MEM_COMMIT||(m.Protect&(PAGE_GUARD|PAGE_NOACCESS)))return false;DWORD p=m.Protect&0xff;return p==PAGE_EXECUTE||p==PAGE_EXECUTE_READ||p==PAGE_EXECUTE_READWRITE||p==PAGE_EXECUTE_WRITECOPY;}
using UnitGuidFn=unsigned long long (__fastcall*)(const char*);
static unsigned long long unitGuid(const char*t){return ((UnitGuidFn)UNIT_GUID_FN)(t);}
static unsigned long objectType(void*o){if(!o||!readable((unsigned char*)o+WoW112::OFF_CGOBJECT_TYPE,4,false))return 0xffffffffUL;return *(unsigned long*)((unsigned char*)o+WoW112::OFF_CGOBJECT_TYPE);}
static unsigned long long objectGuid(void*o){if(!o||!readable((unsigned char*)o+WoW112::OFF_CGOBJECT_GUID,8,false))return 0;return *(unsigned long long*)((unsigned char*)o+WoW112::OFF_CGOBJECT_GUID);}
static void* findVisibleByGuid(unsigned long long guid){if(!guid||!readable((void*)WoW112::OBJECT_MANAGER_PTR,4,false))return 0;unsigned long mgr=*(unsigned long*)WoW112::OBJECT_MANAGER_PTR;if(!mgr||!readable((void*)(mgr+WoW112::OFF_OBJECT_MANAGER_HEAD),4,false))return 0;unsigned long cur=*(unsigned long*)(mgr+WoW112::OFF_OBJECT_MANAGER_HEAD);for(unsigned n=0;cur&&!(cur&1)&&n<4096;++n){void*o=(void*)cur;if(objectGuid(o)==guid)return o;if(!readable((void*)(cur+0x3c),4,false))break;cur=*(unsigned long*)(cur+0x3c);}return 0;}
static void setPrefixedCode(const char*prefix,const char*suffix){char b[96]={0};unsigned n=0;if(prefix)for(;prefix[n]&&n+1<sizeof(b);++n)b[n]=prefix[n];unsigned j=0;while(suffix&&suffix[j]&&n+1<sizeof(b))b[n++]=suffix[j++];b[n]=0;setCode(b);}
static bool descriptor(void*o,unsigned long*desc,const char*prefix){*desc=0;if(!o||!readable((unsigned char*)o+DESC_PTR_OFF,4,false)){setPrefixedCode(prefix,"_DESCRIPTOR_POINTER_UNREADABLE");return false;}unsigned long d=*(unsigned long*)((unsigned char*)o+DESC_PTR_OFF);if(!d||(d&1)){setPrefixedCode(prefix,"_DESCRIPTOR_UNAVAILABLE");return false;}*desc=d;return true;}
static bool descriptorFields(unsigned long d,bool write){unsigned long last=d+PLAYER_VISIBLE_ITEM1_OFF+18UL*VISIBLE_STRIDE+VISIBLE_WORDS*4-4;return readable((void*)(d+DISPLAY_OFF),4,write)&&readable((void*)(d+NATIVE_DISPLAY_OFF),4,false)&&readable((void*)(d+MOUNT_OFF),4,write)&&readable((void*)last,4,write);}
static unsigned long rd(unsigned long d,unsigned long off){return *(volatile unsigned long*)(d+off);}
static void wr(unsigned long d,unsigned long off,unsigned long v){*(volatile unsigned long*)(d+off)=v;}
static bool visible(unsigned long d,int slot,unsigned long**out,bool write){*out=0;if(slot<1||slot>19)return false;unsigned long a=d+PLAYER_VISIBLE_ITEM1_OFF+(unsigned long)(slot-1)*VISIBLE_STRIDE;if(!readable((void*)a,VISIBLE_WORDS*4,write))return false;*out=(unsigned long*)a;return true;}
static unsigned long firstEnchant(const unsigned long*d){if(!d)return 0;for(unsigned i=1;i<=ENCHANT_COUNT;++i)if(d[i])return d[i];return 0;}
static unsigned long firstEnchantSaved(const unsigned long*d){for(unsigned i=0;i<ENCHANT_COUNT;++i)if(d[i])return d[i];return 0;}
using UpdateDisplayFn=void (__thiscall*)(void*);
using RefreshMountFn=void (__thiscall*)(void*,bool);
static bool rebuild(void*o){if(!o||!executable(UPDATE_DISPLAY)){setCode("NATIVE_REBUILD_ADDRESS_UNAVAILABLE");return false;}if(!readable((unsigned char*)o+UNIT_MODEL_PTR_OFF,4,false)||!readable((unsigned char*)o+UNIT_DISPLAY_CACHE_OFF,4,false)){setCode("PLAYER_MODEL_STATE_UNAVAILABLE");return false;}((UpdateDisplayFn)UPDATE_DISPLAY)(o);__sync_synchronize();return true;}
static bool refreshMount(void*o){if(!o||!executable(REFRESH_MOUNT)){setCode("MOUNT_REFRESH_ADDRESS_UNAVAILABLE");return false;}((RefreshMountFn)REFRESH_MOUNT)(o,true);__sync_synchronize();return true;}
static bool refreshEquipment(void*o,unsigned long d){unsigned long cur=rd(d,DISPLAY_OFF);if(!cur){setCode("EQUIPMENT_REFRESH_DISPLAY_ZERO");return false;}unsigned long tmp=cur==EQUIP_TEMP_DISPLAY?EQUIP_FALLBACK_DISPLAY:EQUIP_TEMP_DISPLAY;wr(d,DISPLAY_OFF,tmp);__sync_synchronize();if(!rebuild(o)){wr(d,DISPLAY_OFF,cur);__sync_synchronize();return false;}wr(d,DISPLAY_OFF,cur);__sync_synchronize();if(!rebuild(o))return false;if(rd(d,DISPLAY_OFF)!=cur){setCode("EQUIPMENT_REFRESH_RESTORE_FAILED");return false;}return true;}
static void resetPlayer(unsigned long long guid){bool ac=g.character.autoMaintain,aw=g.weapons.autoMaintain,ag=g.glows.autoMaintain,am=g.mount.autoMaintain;g=State{};g.playerGuid=guid;g.character.autoMaintain=ac;g.weapons.autoMaintain=aw;g.glows.autoMaintain=ag;g.mount.autoMaintain=am;setCode("PLAYER_CHANGED");}
static bool getPlayer(void**o,unsigned long*d){*o=0;*d=0;unsigned long long guid=unitGuid("player");if(!guid){setCode("PLAYER_GUID_UNAVAILABLE");return false;}*o=findVisibleByGuid(guid);if(!*o||objectType(*o)!=WoW112::TYPE_PLAYER){setCode("PLAYER_OBJECT_UNAVAILABLE");return false;}if(g.playerGuid&&g.playerGuid!=guid)resetPlayer(guid);else if(!g.playerGuid)g.playerGuid=guid;if(!descriptor(*o,d,"PLAYER"))return false;if(!descriptorFields(*d,true)){setCode("PLAYER_APPEARANCE_FIELDS_UNAVAILABLE");return false;}return true;}
static bool getTarget(void**o,unsigned long*d,unsigned long*type,bool playerOnly){*o=0;*d=0;*type=0xffffffffUL;setCode("TARGET_NOT_SELECTED");unsigned long long guid=unitGuid("target");if(!guid)return false;*o=findVisibleByGuid(guid);if(!*o){setCode("TARGET_OBJECT_UNAVAILABLE");return false;}*type=objectType(*o);if(playerOnly&&*type!=WoW112::TYPE_PLAYER){setCode("TARGET_NOT_PLAYER");return false;}if(!playerOnly&&*type!=WoW112::TYPE_PLAYER&&*type!=WoW112::TYPE_UNIT){setCode("TARGET_NOT_UNIT");return false;}if(!descriptor(*o,d,"TARGET"))return false;if(!readable((void*)(*d+DISPLAY_OFF),4,false)||!readable((void*)(*d+NATIVE_DISPLAY_OFF),4,false)){setCode("TARGET_DISPLAY_FIELDS_UNAVAILABLE");return false;}if(playerOnly){unsigned long last=*d+PLAYER_VISIBLE_ITEM1_OFF+18UL*VISIBLE_STRIDE+VISIBLE_WORDS*4-4;if(!readable((void*)last,4,false)){setCode("TARGET_VISIBLE_ITEMS_UNAVAILABLE");return false;}}setCode(playerOnly?"TARGET_PLAYER_APPEARANCE_READ":"TARGET_MODEL_READ");return true;}
static bool getPlayerToken(const char*token,void**o,unsigned long*d,unsigned long long*guid){*o=0;*d=0;*guid=0;if(!token||!*token){setCode("SYNC_UNIT_TOKEN_REQUIRED");return false;}*guid=unitGuid(token);if(!*guid){setCode("SYNC_UNIT_GUID_UNAVAILABLE");return false;}*o=findVisibleByGuid(*guid);if(!*o||objectType(*o)!=WoW112::TYPE_PLAYER){setCode("SYNC_PLAYER_NOT_VISIBLE");return false;}if(!descriptor(*o,d,"SYNC_PLAYER"))return false;unsigned long last=*d+PLAYER_VISIBLE_ITEM1_OFF+18UL*VISIBLE_STRIDE+VISIBLE_WORDS*4-4;if(!readable((void*)(*d+DISPLAY_OFF),4,true)||!readable((void*)(*d+MOUNT_OFF),4,true)||!readable((void*)last,4,true)){setCode("SYNC_PLAYER_FIELDS_UNAVAILABLE");return false;}setCode("SYNC_PLAYER_READY");return true;}

static bool allowedGuildName(const char*s){static const unsigned char e[12]={191,254,240,179,194,233,189,255,196,188,244,229};if(!s)return false;for(unsigned i=0;i<12;++i)if((unsigned char)s[i]!=(unsigned char)(e[i]^0x5A))return false;return s[12]==0;}
static bool authorized(Lua50::State L){if(!L)return false;int old=Lua50::GetTop(L);Lua50::GetGlobal(L,"GetGuildInfo");if(!Lua50::IsCFunction(L,-1)){Lua50::SetTop(L,old);return false;}Lua50::CFunction c=Lua50::ToCFunction(L,-1);if(!c||(trustedGuild&&trustedGuild!=c)){Lua50::SetTop(L,old);return false;}Lua50::PushString(L,"player");if(Lua50::PCall(L,1,3,0)!=0){Lua50::SetTop(L,old);return false;}const char*name=Lua50::ToString(L,old+1);bool nonempty=name&&*name;if(nonempty&&!trustedGuild)trustedGuild=c;bool ok=nonempty&&allowedGuildName(name);Lua50::SetTop(L,old);return ok;}
static int fail(Lua50::State L,const char*c){Lua50::PushBool(L,false);Lua50::PushString(L,c);return 2;}
static void opt(Lua50::State L,bool ok,unsigned long v){if(ok)Lua50::PushNumber(L,(double)v);else Lua50::PushNil(L);}

static bool captureCharacter(void**o,unsigned long*d){if(!getPlayer(o,d))return false;if(!g.character.captured){g.character.original=rd(*d,DISPLAY_OFF);g.character.nativeOriginal=rd(*d,NATIVE_DISPLAY_OFF);if(!g.character.original){setCode("ORIGINAL_DISPLAY_ID_ZERO");return false;}g.character.captured=true;setCode("ORIGINAL_CAPTURED");}return true;}
static bool applyCharacter(unsigned long id){if(!id||id>MAX_ID){setCode("DISPLAY_ID_OUT_OF_RANGE");return false;}void*o=0;unsigned long d=0;if(!captureCharacter(&o,&d))return false;wr(d,DISPLAY_OFF,id);__sync_synchronize();if(rd(d,DISPLAY_OFF)!=id){setCode("DISPLAY_WRITE_VERIFY_FAILED");return false;}if(!rebuild(o)){wr(d,DISPLAY_OFF,g.character.original);__sync_synchronize();return false;}g.character.requested=id;g.character.applied=true;setCode("APPLIED_NATIVE_MODEL_REBUILD");return true;}
static bool restoreCharacter(){void*o=0;unsigned long d=0;if(!captureCharacter(&o,&d))return false;wr(d,DISPLAY_OFF,g.character.original);__sync_synchronize();if(rd(d,DISPLAY_OFF)!=g.character.original){setCode("RESTORE_WRITE_VERIFY_FAILED");return false;}if(!rebuild(o))return false;g.character.requested=0;g.character.applied=false;setCode("RESTORED_NATIVE_MODEL_REBUILD");return true;}
static bool refreshCharacter(){void*o=0;unsigned long d=0;if(!captureCharacter(&o,&d))return false;if(!rebuild(o))return false;setCode("NATIVE_MODEL_REBUILD_CALLED");return true;}
static bool maintainCharacter(){if(!g.character.autoMaintain||!g.character.applied||!g.character.requested){setCode("MAINTAIN_IDLE");return true;}void*o=0;unsigned long d=0;if(!captureCharacter(&o,&d))return false;if(rd(d,DISPLAY_OFF)!=g.character.requested){wr(d,DISPLAY_OFF,g.character.requested);__sync_synchronize();if(rd(d,DISPLAY_OFF)!=g.character.requested){setCode("MAINTAIN_WRITE_VERIFY_FAILED");return false;}if(!rebuild(o))return false;setCode("MAINTAIN_REAPPLIED_NATIVE");}else setCode("MAINTAIN_OK");return true;}
static bool captureWeapon(unsigned long d,unsigned i,unsigned long**data){if(i>=3||!visible(d,WEAPON_SLOT[i],data,true)){setCode("WEAPON_SLOT_UNAVAILABLE");return false;}if(!g.weapons.captured[i]){g.weapons.original[i]=(*data)[0];g.weapons.captured[i]=true;}return true;}
static bool applyWeapon(unsigned i,unsigned long id){if(i>=3||id>MAX_ID){setCode("WEAPON_ARGUMENT_OUT_OF_RANGE");return false;}void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;unsigned long*data=0;if(!captureWeapon(d,i,&data))return false;data[0]=id;__sync_synchronize();if(data[0]!=id){setCode("WEAPON_WRITE_VERIFY_FAILED");return false;}if(!refreshEquipment(o,d)){data[0]=g.weapons.original[i];__sync_synchronize();return false;}g.weapons.requested[i]=id;g.weapons.applied[i]=true;setCode("WEAPON_APPLIED");return true;}
static bool restoreWeapons(){void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;bool changed=false;for(unsigned i=0;i<3;++i){if(!g.weapons.captured[i]||!g.weapons.applied[i])continue;unsigned long*data=0;if(!visible(d,WEAPON_SLOT[i],&data,true)){setCode("WEAPON_SLOT_UNAVAILABLE");return false;}data[0]=g.weapons.original[i];g.weapons.applied[i]=false;g.weapons.requested[i]=0;changed=true;}__sync_synchronize();if(changed&&!refreshEquipment(o,d))return false;setCode(changed?"WEAPONS_RESTORED":"WEAPONS_ALREADY_ORIGINAL");return true;}
static bool maintainWeapons(){if(!g.weapons.autoMaintain){setCode("WEAPON_MAINTAIN_IDLE");return true;}void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;bool changed=false;for(unsigned i=0;i<3;++i){if(!g.weapons.applied[i])continue;unsigned long*data=0;if(!visible(d,WEAPON_SLOT[i],&data,true)){setCode("WEAPON_SLOT_UNAVAILABLE");return false;}if(data[0]!=g.weapons.requested[i]){data[0]=g.weapons.requested[i];changed=true;}}__sync_synchronize();if(changed&&!refreshEquipment(o,d))return false;setCode(changed?"WEAPON_MAINTAIN_REAPPLIED":"WEAPON_MAINTAIN_OK");return true;}
static bool captureGlow(unsigned long d,unsigned i,unsigned long**data){if(i>=2||!visible(d,GLOW_SLOT[i],data,true)){setCode("GLOW_SLOT_UNAVAILABLE");return false;}if(!g.glows.captured[i]){for(unsigned n=0;n<ENCHANT_COUNT;++n)g.glows.original[i][n]=(*data)[n+1];g.glows.captured[i]=true;}return true;}
static bool applyGlow(unsigned i,unsigned long id){if(i>=2||id>MAX_ID){setCode("GLOW_ARGUMENT_OUT_OF_RANGE");return false;}void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;unsigned long*data=0;if(!captureGlow(d,i,&data))return false;for(unsigned n=1;n<=ENCHANT_COUNT;++n)data[n]=0;if(id)data[1]=id;__sync_synchronize();if(firstEnchant(data)!=id){setCode("GLOW_WRITE_VERIFY_FAILED");return false;}if(!refreshEquipment(o,d)){for(unsigned n=0;n<ENCHANT_COUNT;++n)data[n+1]=g.glows.original[i][n];__sync_synchronize();return false;}g.glows.requested[i]=id;g.glows.applied[i]=true;setCode(id?"GLOW_APPLIED":"GLOW_CLEARED");return true;}
static bool restoreGlows(){void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;bool changed=false;for(unsigned i=0;i<2;++i){if(!g.glows.captured[i]||!g.glows.applied[i])continue;unsigned long*data=0;if(!visible(d,GLOW_SLOT[i],&data,true)){setCode("GLOW_SLOT_UNAVAILABLE");return false;}for(unsigned n=0;n<ENCHANT_COUNT;++n)data[n+1]=g.glows.original[i][n];g.glows.applied[i]=false;g.glows.requested[i]=0;changed=true;}__sync_synchronize();if(changed&&!refreshEquipment(o,d))return false;setCode(changed?"GLOWS_RESTORED":"GLOWS_ALREADY_ORIGINAL");return true;}
static bool maintainGlows(){if(!g.glows.autoMaintain){setCode("GLOW_MAINTAIN_IDLE");return true;}void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;bool changed=false;for(unsigned i=0;i<2;++i){if(!g.glows.applied[i])continue;unsigned long*data=0;if(!visible(d,GLOW_SLOT[i],&data,true)){setCode("GLOW_SLOT_UNAVAILABLE");return false;}unsigned long want=g.glows.requested[i];if(firstEnchant(data)!=want){for(unsigned n=1;n<=ENCHANT_COUNT;++n)data[n]=0;if(want)data[1]=want;changed=true;}}__sync_synchronize();if(changed&&!refreshEquipment(o,d))return false;setCode(changed?"GLOW_MAINTAIN_REAPPLIED":"GLOW_MAINTAIN_OK");return true;}
static bool captureMount(unsigned long d){if(!g.mount.captured){g.mount.original=rd(d,MOUNT_OFF);g.mount.captured=true;}return true;}
static bool applyMountId(unsigned long id){if(id>MAX_ID){setCode("MOUNT_ARGUMENT_OUT_OF_RANGE");return false;}void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;captureMount(d);wr(d,MOUNT_OFF,id);__sync_synchronize();if(rd(d,MOUNT_OFF)!=id){setCode("MOUNT_WRITE_VERIFY_FAILED");return false;}if(!refreshMount(o)){wr(d,MOUNT_OFF,g.mount.original);__sync_synchronize();return false;}g.mount.requested=id;g.mount.applied=true;setCode(id?"MOUNT_APPLIED":"MOUNT_CLEARED");return true;}
static bool restoreMountId(){void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;if(!g.mount.captured||!g.mount.applied){setCode("MOUNT_ALREADY_ORIGINAL");return true;}wr(d,MOUNT_OFF,g.mount.original);__sync_synchronize();if(rd(d,MOUNT_OFF)!=g.mount.original){setCode("MOUNT_RESTORE_VERIFY_FAILED");return false;}if(!refreshMount(o))return false;g.mount.requested=0;g.mount.applied=false;setCode("MOUNT_RESTORED");return true;}
static bool maintainMountId(){if(!g.mount.autoMaintain||!g.mount.applied){setCode("MOUNT_MAINTAIN_IDLE");return true;}void*o=0;unsigned long d=0;if(!getPlayer(&o,&d))return false;if(rd(d,MOUNT_OFF)!=g.mount.requested){wr(d,MOUNT_OFF,g.mount.requested);__sync_synchronize();if(!refreshMount(o))return false;setCode("MOUNT_MAINTAIN_REAPPLIED");}else setCode("MOUNT_MAINTAIN_OK");return true;}

using SOpen=unsigned long long (__stdcall*)(const char*,void**);
using SRead=unsigned long long (__stdcall*)(void*,void*,unsigned long,unsigned long*,void*,void*);
using SClose=unsigned long long (__stdcall*)(void*);
static bool readExact(void*f,void*b,unsigned long n,SRead r){unsigned long got=0;return r(f,b,n,&got,0,0)!=0&&got==n;}
static bool inventoryMatch(unsigned i,unsigned long t){if(i==0)return t==13||t==17||t==21;if(i==1)return t==13||t==14||t==22||t==23;return t==15||t==25||t==26;}
static void resolveNpcItems(const unsigned long display[3],unsigned long items[3]){items[0]=items[1]=items[2]=0;if(!executable(SFILE_OPEN)||!executable(SFILE_READ)||!executable(SFILE_CLOSE))return;void*f=0;SOpen op=(SOpen)SFILE_OPEN;SRead rr=(SRead)SFILE_READ;SClose cl=(SClose)SFILE_CLOSE;if(!op("DBFilesClient\\Item.dbc",&f)||!f)return;ItemDbHeader h={};if(!readExact(f,&h,sizeof(h),rr)||h.magic[0]!='W'||h.magic[1]!='D'||h.magic[2]!='B'||h.magic[3]!='C'||h.fieldCount<7||h.recordSize<28||!h.recordCount){cl(f);return;}unsigned long long bytes=(unsigned long long)h.recordCount*h.recordSize;if(bytes>64ULL*1024*1024){cl(f);return;}unsigned char*buf=(unsigned char*)VirtualAlloc(0,(unsigned long)bytes,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE);if(!buf){cl(f);return;}bool ok=readExact(f,buf,(unsigned long)bytes,rr);cl(f);if(ok){unsigned long fallback[3]={0,0,0};for(unsigned long r=0;r<h.recordCount;++r){unsigned long*w=(unsigned long*)(buf+r*h.recordSize);unsigned long item=w[0],disp=w[5],type=w[6];for(unsigned i=0;i<3;++i)if(display[i]&&disp==display[i]){if(!fallback[i])fallback[i]=item;if(!items[i]&&inventoryMatch(i,type))items[i]=item;}}for(unsigned i=0;i<3;++i)if(!items[i])items[i]=fallback[i];}VirtualFree(buf,0,MEM_RELEASE);}

static Snapshot localSnapshot(){Snapshot s={};if(g.character.applied){s.flags|=SYNC_CHARACTER;s.character=g.character.requested;}if(g.weapons.applied[0]){s.flags|=SYNC_WMAIN;s.wmain=g.weapons.requested[0];}if(g.weapons.applied[1]){s.flags|=SYNC_WOFF;s.woff=g.weapons.requested[1];}if(g.weapons.applied[2]){s.flags|=SYNC_WRANGED;s.wranged=g.weapons.requested[2];}if(g.glows.applied[0]){s.flags|=SYNC_GMAIN;s.gmain=g.glows.requested[0];}if(g.glows.applied[1]){s.flags|=SYNC_GOFF;s.goff=g.glows.requested[1];}if(g.mount.applied){s.flags|=SYNC_MOUNT;s.mount=g.mount.requested;}return s;}
static bool snapshotValid(const Snapshot&s){return (s.flags&~DA_ALLOWED_FLAGS)==0&&s.character<=MAX_ID&&s.wmain<=MAX_ID&&s.woff<=MAX_ID&&s.wranged<=MAX_ID&&s.gmain<=MAX_ID&&s.goff<=MAX_ID&&s.mount<=MAX_ID&&(!(s.flags&SYNC_CHARACTER)||s.character!=0);}
static unsigned long long rol(unsigned long long x,int b){return (x<<b)|(x>>(64-b));}
static void sip(unsigned long long&v0,unsigned long long&v1,unsigned long long&v2,unsigned long long&v3){v0+=v1;v1=rol(v1,13);v1^=v0;v0=rol(v0,32);v2+=v3;v3=rol(v3,16);v3^=v2;v0+=v3;v3=rol(v3,21);v3^=v0;v2+=v1;v1=rol(v1,17);v1^=v2;v2=rol(v2,32);}
static unsigned long long rd64(const unsigned char*p){unsigned long long v=0;for(int i=0;i<8;++i)v|=((unsigned long long)p[i])<<(i*8);return v;}
static unsigned long long mac(const unsigned char*d,unsigned n){unsigned long long v0=0x736f6d6570736575ULL^KEY0^DA_DOMAIN,v1=0x646f72616e646f6dULL^KEY1,v2=0x6c7967656e657261ULL^KEY0,v3=0x7465646279746573ULL^KEY1^DA_DOMAIN;unsigned at=0;while(at+8<=n){unsigned long long m=rd64(d+at);v3^=m;sip(v0,v1,v2,v3);sip(v0,v1,v2,v3);v0^=m;at+=8;}unsigned long long tail=((unsigned long long)n)<<56;for(unsigned i=0;at+i<n;++i)tail|=((unsigned long long)d[at+i])<<(i*8);v3^=tail;sip(v0,v1,v2,v3);sip(v0,v1,v2,v3);v0^=tail;v2^=0xff;for(int i=0;i<4;++i)sip(v0,v1,v2,v3);return v0^v1^v2^v3;}
static bool put8(Buf&b,unsigned v){if(b.n+1>sizeof(b.d))return false;b.d[b.n++]=(unsigned char)v;return true;}static bool put16(Buf&b,unsigned v){return put8(b,v)&&put8(b,v>>8);}static bool put32(Buf&b,unsigned long v){for(int i=0;i<4;++i)if(!put8(b,v>>(8*i)))return false;return true;}static bool put64(Buf&b,unsigned long long v){for(int i=0;i<8;++i)if(!put8(b,(unsigned)(v>>(8*i))))return false;return true;}
static bool take8(const Buf&b,unsigned&at,unsigned*o){if(at+1>b.n)return false;*o=b.d[at++];return true;}static bool take16(const Buf&b,unsigned&at,unsigned*o){unsigned a=0,c=0;if(!take8(b,at,&a)||!take8(b,at,&c))return false;*o=a|(c<<8);return true;}static bool take32(const Buf&b,unsigned&at,unsigned long*o){if(at+4>b.n)return false;unsigned long v=0;for(int i=0;i<4;++i)v|=((unsigned long)b.d[at+i])<<(8*i);at+=4;*o=v;return true;}static bool take64(const Buf&b,unsigned&at,unsigned long long*o){if(at+8>b.n)return false;*o=rd64(b.d+at);at+=8;return true;}
static int b64c(char c){if(c>='A'&&c<='Z')return c-'A';if(c>='a'&&c<='z')return c-'a'+26;if(c>='0'&&c<='9')return c-'0'+52;if(c=='-')return 62;if(c=='_')return 63;return -1;}
static bool b64enc(const Buf&b,char*out,unsigned cap){unsigned acc=0;int bits=0,j=0;for(unsigned i=0;i<b.n;++i){acc=(acc<<8)|b.d[i];bits+=8;while(bits>=6){bits-=6;if((unsigned)j+1>=cap)return false;out[j++]=B64[(acc>>bits)&63];}}if(bits>0){if((unsigned)j+1>=cap)return false;out[j++]=B64[(acc<<(6-bits))&63];}out[j]=0;return true;}
static bool b64dec(const char*s,Buf&b){b.n=0;unsigned n=slen(s);if(!n||n>252)return false;unsigned acc=0;int bits=0;for(unsigned i=0;i<n;++i){int v=b64c(s[i]);if(v<0)return false;acc=(acc<<6)|(unsigned)v;bits+=6;if(bits>=8){bits-=8;if(b.n>=sizeof(b.d))return false;b.d[b.n++]=(unsigned char)((acc>>bits)&255);}}return true;}
static unsigned long nameHash(const char*s){unsigned long h=2166136261UL;for(unsigned i=0;s&&s[i]&&s[i]!='-';++i){char c=s[i];if(c>='A'&&c<='Z')c+=32;h^=(unsigned char)c;h*=16777619UL;}return h;}
static unsigned long epochNow(){SYSTEMTIME t={};GetSystemTime(&t);auto leap=[](unsigned y){return (y%4==0&&y%100!=0)||y%400==0;};static const unsigned md[12]={31,28,31,30,31,30,31,31,30,31,30,31};unsigned long days=0;for(unsigned y=1970;y<t.wYear;++y)days+=leap(y)?366:365;for(unsigned m=1;m<t.wMonth;++m){days+=md[m-1];if(m==2&&leap(t.wYear))days++;}days+=t.wDay-1;return days*86400UL+t.wHour*3600UL+t.wMinute*60UL+t.wSecond;}
static bool remember(unsigned long sh,unsigned long issued,unsigned long nonce,unsigned long long sig){Replay*empty=0,*old=0;for(auto&r:replay){if(r.active&&r.sender==sh&&r.issued==issued&&r.nonce==nonce&&r.sig==sig)return false;if(!r.active&&!empty)empty=&r;if(r.active&&(!old||(long)(r.touched-old->touched)<0))old=&r;}Replay*x=empty?empty:old;if(!x)return false;x->active=true;x->sender=sh;x->issued=issued;x->nonce=nonce;x->sig=sig;x->touched=GetTickCount();return true;}
static bool buildPacket(const Snapshot&s,const char*sender,char*out,unsigned cap,const char**reason){if(!sender||!*sender){*reason="DA_PACKET_SENDER_REQUIRED";return false;}if(!snapshotValid(s)){*reason="DA_PACKET_VALUES_INVALID";return false;}Buf b={};unsigned long issued=epochNow(),nonce=++nonceCounter;put8(b,DA_PACKET_VERSION);put16(b,s.flags);put32(b,s.character);put32(b,s.wmain);put32(b,s.woff);put32(b,s.wranged);put32(b,s.gmain);put32(b,s.goff);put32(b,s.mount);put32(b,issued);put32(b,nonce);put32(b,nameHash(sender));put64(b,mac(b.d,b.n));if(!b64enc(b,out,cap)||slen(out)>245){*reason="DA_PACKET_TOO_LONG";return false;}*reason="OK";return true;}
static bool openPacket(const char*packet,const char*sender,Snapshot*out,const char**reason){Buf b={};if(!b64dec(packet,b)||b.n!=51){*reason="DA_PACKET_INVALID";return false;}unsigned signedN=b.n-8,at=signedN;unsigned long long supplied=0;if(!take64(b,at,&supplied)||supplied!=mac(b.d,signedN)){*reason="DA_PACKET_SIGNATURE_INVALID";return false;}at=0;unsigned ver=0,flags=0;unsigned long issued=0,nonce=0,sh=0;Snapshot s={};if(!take8(b,at,&ver)||ver!=DA_PACKET_VERSION||!take16(b,at,&flags)||!take32(b,at,&s.character)||!take32(b,at,&s.wmain)||!take32(b,at,&s.woff)||!take32(b,at,&s.wranged)||!take32(b,at,&s.gmain)||!take32(b,at,&s.goff)||!take32(b,at,&s.mount)||!take32(b,at,&issued)||!take32(b,at,&nonce)||!take32(b,at,&sh)||at!=signedN){*reason="DA_PACKET_FORMAT_INVALID";return false;}s.flags=(unsigned short)flags;if(!sender||!*sender||sh!=nameHash(sender)){*reason="DA_PACKET_SENDER_MISMATCH";return false;}if(!snapshotValid(s)){*reason="DA_PACKET_VALUES_INVALID";return false;}unsigned long now=epochNow(),age=now>=issued?now-issued:issued-now;if(age>PACKET_LIFETIME){*reason="DA_PACKET_EXPIRED";return false;}if(!remember(sh,issued,nonce,supplied)){*reason="DA_PACKET_REPLAYED";return false;}*out=s;*reason="OK";return true;}
static void normalizeSender(const char*in,char*out,unsigned cap){unsigned j=0;for(unsigned i=0;in&&in[i]&&in[i]!='-'&&j+1<cap;++i){char c=in[i];if(c>='A'&&c<='Z')c+=32;out[j++]=c;}out[j]=0;}
static SenderSnapshot* senderSlot(const char*sender,bool create){char n[64]={};normalizeSender(sender,n,sizeof(n));SenderSnapshot*empty=0;for(auto&s:senders){if(s.active&&eqI(s.sender,n))return &s;if(!s.active&&!empty)empty=&s;}if(create&&empty){*empty=SenderSnapshot{};empty->active=true;cpy(empty->sender,sizeof(empty->sender),n);return empty;}return 0;}
static RemoteState* remoteSlot(unsigned long long guid,bool create){RemoteState*empty=0;for(auto&r:remotes){if(r.active&&r.guid==guid)return &r;if(!r.active&&!empty)empty=&r;}if(create&&empty){*empty=RemoteState{};empty->active=true;empty->guid=guid;return empty;}return 0;}
static bool captureRemote(RemoteState&r,unsigned long d){if(r.captured)return true;r.originalDisplay=rd(d,DISPLAY_OFF);r.originalMount=rd(d,MOUNT_OFF);for(unsigned i=0;i<3;++i){unsigned long*x=0;if(!visible(d,WEAPON_SLOT[i],&x,true))return false;r.originalWeapons[i]=x[0];}for(unsigned i=0;i<2;++i){unsigned long*x=0;if(!visible(d,GLOW_SLOT[i],&x,true))return false;for(unsigned n=0;n<ENCHANT_COUNT;++n)r.originalGlows[i][n]=x[n+1];}r.captured=true;return true;}
static bool applyRemote(const char*token,const Snapshot&s){if(!snapshotValid(s)){setCode("SYNC_SNAPSHOT_VALUES_INVALID");return false;}void*o=0;unsigned long d=0;unsigned long long guid=0;if(!getPlayerToken(token,&o,&d,&guid))return false;RemoteState*r=remoteSlot(guid,true);if(!r){setCode("SYNC_REMOTE_CAPACITY");return false;}if(!captureRemote(*r,d)){setCode("SYNC_CAPTURE_ORIGINAL_FAILED");return false;}unsigned short prev=r->snap.flags;bool disp=false,mount=false;if(!(prev&SYNC_CHARACTER))r->originalDisplay=rd(d,DISPLAY_OFF);if(s.flags&SYNC_CHARACTER){if(rd(d,DISPLAY_OFF)!=s.character){wr(d,DISPLAY_OFF,s.character);disp=true;}}else if(prev&SYNC_CHARACTER){if(rd(d,DISPLAY_OFF)!=r->originalDisplay){wr(d,DISPLAY_OFF,r->originalDisplay);disp=true;}}
unsigned long weapons[3]={s.wmain,s.woff,s.wranged};unsigned short wf[3]={SYNC_WMAIN,SYNC_WOFF,SYNC_WRANGED};for(unsigned i=0;i<3;++i){unsigned long*x=0;if(!visible(d,WEAPON_SLOT[i],&x,true))return false;if(!(prev&wf[i]))r->originalWeapons[i]=x[0];if(s.flags&wf[i]){if(x[0]!=weapons[i]){x[0]=weapons[i];disp=true;}}else if(prev&wf[i]&&x[0]!=r->originalWeapons[i]){x[0]=r->originalWeapons[i];disp=true;}}
unsigned long gl[2]={s.gmain,s.goff};unsigned short gf[2]={SYNC_GMAIN,SYNC_GOFF};for(unsigned i=0;i<2;++i){unsigned long*x=0;if(!visible(d,GLOW_SLOT[i],&x,true))return false;if(!(prev&gf[i]))for(unsigned n=0;n<ENCHANT_COUNT;++n)r->originalGlows[i][n]=x[n+1];if(s.flags&gf[i]){if(firstEnchant(x)!=gl[i]){for(unsigned n=1;n<=ENCHANT_COUNT;++n)x[n]=0;if(gl[i])x[1]=gl[i];disp=true;}}else if(prev&gf[i]){bool diff=false;for(unsigned n=0;n<ENCHANT_COUNT;++n)if(x[n+1]!=r->originalGlows[i][n])diff=true;if(diff){for(unsigned n=0;n<ENCHANT_COUNT;++n)x[n+1]=r->originalGlows[i][n];disp=true;}}}
if(!(prev&SYNC_MOUNT))r->originalMount=rd(d,MOUNT_OFF);if(s.flags&SYNC_MOUNT){if(rd(d,MOUNT_OFF)!=s.mount){wr(d,MOUNT_OFF,s.mount);mount=true;}}else if(prev&SYNC_MOUNT){if(rd(d,MOUNT_OFF)!=r->originalMount){wr(d,MOUNT_OFF,r->originalMount);mount=true;}}__sync_synchronize();if(disp&&!refreshEquipment(o,d))return false;if(mount&&!refreshMount(o))return false;r->snap=s;setCode("SYNC_REMOTE_APPLIED");return true;}
static bool restoreRemote(unsigned long long guid){RemoteState*r=remoteSlot(guid,false);if(!r)return true;void*o=findVisibleByGuid(guid);if(!o||objectType(o)!=WoW112::TYPE_PLAYER){*r=RemoteState{};return true;}unsigned long d=0;if(!descriptor(o,&d,"SYNC_RESTORE"))return false;wr(d,DISPLAY_OFF,r->originalDisplay);wr(d,MOUNT_OFF,r->originalMount);for(unsigned i=0;i<3;++i){unsigned long*x=0;if(!visible(d,WEAPON_SLOT[i],&x,true))return false;x[0]=r->originalWeapons[i];}for(unsigned i=0;i<2;++i){unsigned long*x=0;if(!visible(d,GLOW_SLOT[i],&x,true))return false;for(unsigned n=0;n<ENCHANT_COUNT;++n)x[n+1]=r->originalGlows[i][n];}__sync_synchronize();refreshEquipment(o,d);refreshMount(o);*r=RemoteState{};return true;}
static void clearRemoteMemory(){for(auto&r:remotes)r=RemoteState{};for(auto&s:senders)s=SenderSnapshot{};for(auto&r:replay)r=Replay{};}

static int charStatus(Lua50::State L){void*o=0;unsigned long d=0;bool ready=getPlayer(&o,&d);if(ready&&!g.character.captured){g.character.original=rd(d,DISPLAY_OFF);g.character.nativeOriginal=rd(d,NATIVE_DISPLAY_OFF);g.character.captured=g.character.original!=0;if(eqI(g.last,"NOT_INITIALIZED"))setCode("READY");}Lua50::PushBool(L,true);Lua50::PushBool(L,ready);Lua50::PushString(L,g.last);opt(L,ready,ready?rd(d,DISPLAY_OFF):0);opt(L,ready,ready?rd(d,NATIVE_DISPLAY_OFF):0);opt(L,g.character.captured,g.character.original);opt(L,g.character.applied,g.character.requested);Lua50::PushBool(L,g.character.applied);Lua50::PushBool(L,g.character.autoMaintain);return 9;}
static int charOp(Lua50::State L,bool ok){void*o=0;unsigned long d=0;bool ready=getPlayer(&o,&d);Lua50::PushBool(L,ok);Lua50::PushString(L,g.last);opt(L,g.character.captured,g.character.original);opt(L,ready,ready?rd(d,DISPLAY_OFF):0);opt(L,g.character.applied,g.character.requested);return 5;}
static int simple(Lua50::State L,bool ok){Lua50::PushBool(L,ok);Lua50::PushString(L,g.last);return 2;}
static int targetModel(Lua50::State L){void*o=0;unsigned long d=0,t=0;bool ok=getTarget(&o,&d,&t,false);unsigned long cur=ok?rd(d,DISPLAY_OFF):0;if(ok&&!cur){ok=false;setCode("TARGET_DISPLAY_ID_ZERO");}Lua50::PushBool(L,ok);Lua50::PushString(L,g.last);opt(L,ok,cur);opt(L,ok,ok?rd(d,NATIVE_DISPLAY_OFF):0);if(ok)Lua50::PushNumber(L,(double)t);else Lua50::PushNil(L);return 5;}
static int weaponStatus(Lua50::State L){void*o=0;unsigned long d=0;bool ready=getPlayer(&o,&d);Lua50::PushBool(L,ready);Lua50::PushString(L,g.last);for(unsigned i=0;i<3;++i){unsigned long*x=0;bool have=ready&&visible(d,WEAPON_SLOT[i],&x,false);opt(L,have,have?x[0]:0);}for(unsigned i=0;i<3;++i)opt(L,g.weapons.captured[i],g.weapons.original[i]);for(unsigned i=0;i<3;++i)opt(L,g.weapons.applied[i],g.weapons.requested[i]);for(unsigned i=0;i<3;++i)Lua50::PushBool(L,g.weapons.applied[i]);Lua50::PushBool(L,g.weapons.autoMaintain);return 15;}
static int targetWeapons(Lua50::State L){void*o=0;unsigned long d=0,t=0;bool ok=getTarget(&o,&d,&t,true);Lua50::PushBool(L,ok);Lua50::PushString(L,g.last);for(unsigned i=0;i<3;++i){unsigned long*x=0;bool have=ok&&visible(d,WEAPON_SLOT[i],&x,false);opt(L,have,have?x[0]:0);}return 5;}
static int targetNpcWeapons(Lua50::State L){void*o=0;unsigned long d=0,t=0;bool ok=getTarget(&o,&d,&t,false);if(ok&&t!=WoW112::TYPE_UNIT){ok=false;setCode("TARGET_NOT_NPC");}unsigned long disp[3]={0,0,0};if(ok){if(!readable((void*)(d+VIRTUAL_ITEM_OFF),12,false)){ok=false;setCode("TARGET_NPC_WEAPONS_UNAVAILABLE");}else{unsigned long*x=(unsigned long*)(d+VIRTUAL_ITEM_OFF);for(unsigned i=0;i<3;++i)disp[i]=x[i];setCode("TARGET_NPC_WEAPONS_READ");}}unsigned long items[3]={0,0,0};if(ok)resolveNpcItems(disp,items);Lua50::PushBool(L,ok);Lua50::PushString(L,g.last);for(unsigned i=0;i<3;++i)opt(L,ok,disp[i]);for(unsigned i=0;i<3;++i)opt(L,ok,items[i]);return 8;}
static int glowStatus(Lua50::State L){void*o=0;unsigned long d=0;bool ready=getPlayer(&o,&d);Lua50::PushBool(L,ready);Lua50::PushString(L,g.last);for(unsigned i=0;i<2;++i){unsigned long*x=0;bool have=ready&&visible(d,GLOW_SLOT[i],&x,false);opt(L,have,have?firstEnchant(x):0);}for(unsigned i=0;i<2;++i)opt(L,g.glows.captured[i],firstEnchantSaved(g.glows.original[i]));for(unsigned i=0;i<2;++i)opt(L,g.glows.applied[i],g.glows.requested[i]);for(unsigned i=0;i<2;++i)Lua50::PushBool(L,g.glows.applied[i]);Lua50::PushBool(L,g.glows.autoMaintain);return 11;}
static int targetGlows(Lua50::State L){void*o=0;unsigned long d=0,t=0;bool ok=getTarget(&o,&d,&t,true);Lua50::PushBool(L,ok);Lua50::PushString(L,g.last);for(unsigned i=0;i<2;++i){unsigned long*x=0;bool have=ok&&visible(d,GLOW_SLOT[i],&x,false);opt(L,have,have?firstEnchant(x):0);}return 4;}
static int mountStatus(Lua50::State L){void*o=0;unsigned long d=0;bool ready=getPlayer(&o,&d);if(ready&&!g.mount.captured)captureMount(d);Lua50::PushBool(L,ready);Lua50::PushString(L,g.last);opt(L,ready,ready?rd(d,MOUNT_OFF):0);opt(L,g.mount.captured,g.mount.original);opt(L,g.mount.applied,g.mount.requested);Lua50::PushBool(L,g.mount.applied);Lua50::PushBool(L,g.mount.autoMaintain);return 7;}
static int targetMount(Lua50::State L,bool requirePlayer){void*o=0;unsigned long d=0,t=0;bool ok=getTarget(&o,&d,&t,requirePlayer);if(ok&&!requirePlayer&&t!=WoW112::TYPE_UNIT){ok=false;setCode("TARGET_NOT_NPC");}if(ok&&!readable((void*)(d+MOUNT_OFF),4,false)){ok=false;setCode("TARGET_MOUNT_FIELD_UNAVAILABLE");}if(ok)setCode(requirePlayer?"TARGET_PLAYER_MOUNT_READ":"TARGET_NPC_MOUNT_READ");Lua50::PushBool(L,ok);Lua50::PushString(L,g.last);opt(L,ok,ok?rd(d,MOUNT_OFF):0);return 3;}
static bool parseIndex(Lua50::State L,unsigned count,unsigned*index,unsigned long*value,const char*code){if(Lua50::GetTop(L)<3||!Lua50::IsNumber(L,2)||!Lua50::IsNumber(L,3)){setCode(code);return false;}double ri=Lua50::ToNumber(L,2),rv=Lua50::ToNumber(L,3);if(ri<1||ri>(double)count||rv<0||rv>(double)MAX_ID){setCode(code);return false;}*index=(unsigned)(ri-1);*value=(unsigned long)rv;return true;}

static int dispatchSharedSyncSuffix(Lua50::State L,const char*s){
if(!s||!startsI(s,"Sync."))return -1;
if(eqI(s,"Sync.Build")||eqI(s,"Sync.BuildClear")){if(Lua50::GetTop(L)<2||!Lua50::IsString(L,2))return fail(L,"SYNC_SENDER_REQUIRED");Snapshot snap=eqI(s,"Sync.Build")?localSnapshot():Snapshot{};char pkt[128]={};const char*r=0;bool ok=buildPacket(snap,Lua50::ToString(L,2),pkt,sizeof(pkt),&r);Lua50::PushBool(L,ok);Lua50::PushString(L,ok?pkt:r);return 2;}
if(eqI(s,"Sync.Receive")){if(Lua50::GetTop(L)<4||!Lua50::IsString(L,2)||!Lua50::IsString(L,3)||!Lua50::IsString(L,4))return fail(L,"SYNC_ARGUMENTS_REQUIRED");Snapshot snap={};const char*r=0;if(!openPacket(Lua50::ToString(L,2),Lua50::ToString(L,3),&snap,&r))return fail(L,r);SenderSnapshot*ss=senderSlot(Lua50::ToString(L,3),true);if(!ss)return fail(L,"SYNC_SENDER_CAPACITY");ss->snap=snap;bool ok=applyRemote(Lua50::ToString(L,4),snap);return simple(L,ok);}
if(eqI(s,"Sync.Reapply")){if(Lua50::GetTop(L)<3||!Lua50::IsString(L,2)||!Lua50::IsString(L,3))return fail(L,"SYNC_REAPPLY_ARGUMENTS_REQUIRED");SenderSnapshot*ss=senderSlot(Lua50::ToString(L,2),false);if(!ss)return fail(L,"SYNC_SNAPSHOT_NOT_FOUND");return simple(L,applyRemote(Lua50::ToString(L,3),ss->snap));}
if(eqI(s,"Sync.RestoreSender")){if(Lua50::GetTop(L)<3||!Lua50::IsString(L,2)||!Lua50::IsString(L,3))return fail(L,"SYNC_RESTORE_ARGUMENTS_REQUIRED");unsigned long long guid=unitGuid(Lua50::ToString(L,3));bool ok=!guid||restoreRemote(guid);SenderSnapshot*ss=senderSlot(Lua50::ToString(L,2),false);if(ss)*ss=SenderSnapshot{};Lua50::PushBool(L,ok);Lua50::PushString(L,ok?"SYNC_REMOTE_RESTORED":"SYNC_REMOTE_RESTORE_FAILED");return 2;}
if(eqI(s,"Sync.RestoreAll")){bool ok=true;unsigned long long ids[REMOTE_LIMIT]={};unsigned n=0;for(auto&r:remotes)if(r.active&&n<REMOTE_LIMIT)ids[n++]=r.guid;for(unsigned i=0;i<n;++i)if(!restoreRemote(ids[i]))ok=false;for(auto&x:senders)x=SenderSnapshot{};Lua50::PushBool(L,ok);Lua50::PushString(L,ok?"SYNC_ALL_RESTORED":"SYNC_RESTORE_PARTIAL");return 2;}
return -1;
}

} // namespace

bool isSharedSyncCommand(const char*cmd){return sharedSyncSuffix(cmd)!=0;}
int dispatchSharedSync(Lua50::State L,const char*cmd){const char*s=sharedSyncSuffix(cmd);return s?dispatchSharedSyncSuffix(L,s):-1;}

int dispatch(Lua50::State L,const char*cmd,bool featureEnabled){const char*s=suffix(cmd);if(!s)return -1;if(isSync(cmd))return dispatchSharedSyncSuffix(L,s);if(!featureEnabled){Lua50::PushBool(L,false);Lua50::PushString(L,"FEATURE_DISABLED");Lua50::PushString(L,"DreamAvatar feature is disabled");return 3;}if(!authorized(L))return fail(L,"ACCESS_DENIED");
if(eqI(s,"Status"))return charStatus(L);if(eqI(s,"GetTargetModel"))return targetModel(L);if(eqI(s,"GetOriginal")){void*o=0;unsigned long d=0;bool ok=captureCharacter(&o,&d);Lua50::PushBool(L,ok);Lua50::PushString(L,g.last);opt(L,g.character.captured,g.character.original);opt(L,g.character.captured,g.character.nativeOriginal);return 4;}
if(eqI(s,"Apply")){if(Lua50::GetTop(L)<2||!Lua50::IsNumber(L,2)){setCode("DISPLAY_ID_REQUIRED");return charOp(L,false);}double v=Lua50::ToNumber(L,2);return charOp(L,v>=1&&v<=MAX_ID?applyCharacter((unsigned long)v):(setCode("DISPLAY_ID_OUT_OF_RANGE"),false));}
if(eqI(s,"Restore"))return charOp(L,restoreCharacter());if(eqI(s,"Refresh"))return charOp(L,refreshCharacter());if(eqI(s,"Maintain"))return charOp(L,maintainCharacter());if(eqI(s,"SetAutoMaintain")){if(Lua50::GetTop(L)<2){setCode("AUTO_MAINTAIN_VALUE_REQUIRED");return charOp(L,false);}g.character.autoMaintain=Lua50::ToBoolean(L,2);setCode(g.character.autoMaintain?"AUTO_MAINTAIN_ENABLED":"AUTO_MAINTAIN_DISABLED");return charOp(L,true);}
if(eqI(s,"WeaponStatus"))return weaponStatus(L);if(eqI(s,"GetTargetWeapons"))return targetWeapons(L);if(eqI(s,"GetTargetNpcWeapons"))return targetNpcWeapons(L);if(eqI(s,"ApplyWeapon")){unsigned i=0;unsigned long v=0;if(!parseIndex(L,3,&i,&v,"WEAPON_ARGUMENT_REQUIRED"))return simple(L,false);return simple(L,applyWeapon(i,v));}if(eqI(s,"RestoreWeapons"))return simple(L,restoreWeapons());if(eqI(s,"MaintainWeapons"))return simple(L,maintainWeapons());if(eqI(s,"SetAutoMaintainWeapons")){if(Lua50::GetTop(L)<2){setCode("AUTO_WEAPONS_VALUE_REQUIRED");return simple(L,false);}g.weapons.autoMaintain=Lua50::ToBoolean(L,2);setCode(g.weapons.autoMaintain?"AUTO_WEAPONS_ENABLED":"AUTO_WEAPONS_DISABLED");return simple(L,true);}
if(eqI(s,"GlowStatus"))return glowStatus(L);if(eqI(s,"GetTargetGlows"))return targetGlows(L);if(eqI(s,"ApplyGlow")){unsigned i=0;unsigned long v=0;if(!parseIndex(L,2,&i,&v,"GLOW_ARGUMENT_REQUIRED"))return simple(L,false);return simple(L,applyGlow(i,v));}if(eqI(s,"RestoreGlows"))return simple(L,restoreGlows());if(eqI(s,"MaintainGlows"))return simple(L,maintainGlows());if(eqI(s,"SetAutoMaintainGlows")){if(Lua50::GetTop(L)<2){setCode("AUTO_GLOWS_VALUE_REQUIRED");return simple(L,false);}g.glows.autoMaintain=Lua50::ToBoolean(L,2);setCode(g.glows.autoMaintain?"AUTO_GLOWS_ENABLED":"AUTO_GLOWS_DISABLED");return simple(L,true);}
if(eqI(s,"MountStatus"))return mountStatus(L);if(eqI(s,"GetTargetPlayerMount"))return targetMount(L,true);if(eqI(s,"GetTargetNpcMount"))return targetMount(L,false);if(eqI(s,"ApplyMount")){if(Lua50::GetTop(L)<2||!Lua50::IsNumber(L,2)){setCode("MOUNT_DISPLAY_ID_REQUIRED");return simple(L,false);}double v=Lua50::ToNumber(L,2);if(v<0||v>MAX_ID){setCode("MOUNT_ARGUMENT_OUT_OF_RANGE");return simple(L,false);}return simple(L,applyMountId((unsigned long)v));}if(eqI(s,"RestoreMount"))return simple(L,restoreMountId());if(eqI(s,"MaintainMount"))return simple(L,maintainMountId());if(eqI(s,"SetAutoMaintainMount")){if(Lua50::GetTop(L)<2){setCode("AUTO_MOUNT_VALUE_REQUIRED");return simple(L,false);}g.mount.autoMaintain=Lua50::ToBoolean(L,2);setCode(g.mount.autoMaintain?"AUTO_MOUNT_ENABLED":"AUTO_MOUNT_DISABLED");return simple(L,true);}
setCode("UNKNOWN_COMMAND");return simple(L,false);}

int dispatchDreamWeaponShared(Lua50::State L,const char*s){
if(!s)return -1;
// Public local weapon operations: no DreamAvatar guild gate.
if(eqI(s,"Status")||eqI(s,"WeaponStatus"))return weaponStatus(L);
if(eqI(s,"GetTargetWeapons"))return targetWeapons(L);
if(eqI(s,"GetTargetNpcWeapons"))return targetNpcWeapons(L);
if(eqI(s,"ApplyWeapon")){unsigned i=0;unsigned long v=0;if(!parseIndex(L,3,&i,&v,"WEAPON_ARGUMENT_REQUIRED"))return simple(L,false);return simple(L,applyWeapon(i,v));}
if(eqI(s,"RestoreWeapons"))return simple(L,restoreWeapons());
if(eqI(s,"MaintainWeapons"))return simple(L,maintainWeapons());
if(eqI(s,"SetAutoMaintainWeapons")){if(Lua50::GetTop(L)<2){setCode("AUTO_WEAPONS_VALUE_REQUIRED");return simple(L,false);}g.weapons.autoMaintain=Lua50::ToBoolean(L,2);setCode(g.weapons.autoMaintain?"AUTO_WEAPONS_ENABLED":"AUTO_WEAPONS_DISABLED");return simple(L,true);}
// DW5 shared DAS1 path: same packet builder, replay protection, sender cache,
// remote capture/apply/restore and reapply state machine used by DreamAvatar.
// Sync is a shared appearance transport and carries all seven appearance fields
// (character, three weapons, two glows, mount). It never uses the local-edit auth gate.
if(startsI(s,"Sync."))return dispatchSharedSyncSuffix(L,s);
Lua50::PushBool(L,false);Lua50::PushString(L,"DREAMWEAPON_COMMAND_DISABLED");Lua50::PushString(L,"DreamWeapon exposes weapon controls and signed synchronization only");return 3;
}
void shutdownDreamWeaponShared(Lua50::State L){
// DreamWeapon owns only the local weapon editor. Shared DAS1 remote/sender state
// must survive a DreamWeapon feature toggle because Sync is not a weapon feature.
if(L&&(g.weapons.applied[0]||g.weapons.applied[1]||g.weapons.applied[2]))restoreWeapons();
g.weapons=WeaponState{};
}

void onWorldLeaving(Lua50::State){}
void onWorldEntering(Lua50::State){}
void shutdownRestricted(Lua50::State L){
// Disabling DreamAvatar revokes/restores only its authorized local editors.
// Shared DAS1 receive/reapply state is independent and must not be destroyed.
if(L){if(g.glows.applied[0]||g.glows.applied[1])restoreGlows();if(g.mount.applied)restoreMountId();if(g.character.applied)restoreCharacter();}
g.character=CharacterState{};g.glows=GlowState{};g.mount=MountState{};trustedGuild=0;setCode("DREAMAVATAR_RESTRICTED_SHUTDOWN");}
void shutdown(Lua50::State L){if(L){unsigned long long ids[REMOTE_LIMIT]={};unsigned n=0;for(auto&r:remotes)if(r.active&&n<REMOTE_LIMIT)ids[n++]=r.guid;for(unsigned i=0;i<n;++i)restoreRemote(ids[i]);if(g.glows.applied[0]||g.glows.applied[1])restoreGlows();if(g.weapons.applied[0]||g.weapons.applied[1]||g.weapons.applied[2])restoreWeapons();if(g.mount.applied)restoreMountId();if(g.character.applied)restoreCharacter();}g=State{};clearRemoteMemory();trustedGuild=0;}
const char* status(){return runtimeStatus;}
}
