#include <windows.h>
#include "moonmarker_advanced.h"
#include "m2scan_media.h"
#include "visual_native.h"
#include "wow112_offsets.h"

namespace TysMoonAdvanced {
namespace {

constexpr unsigned MAX_PATH_LEN=240;
constexpr unsigned NETWORK_PATH_LEN=140;
constexpr float MIN_SCALE=0.10f,MAX_SCALE=5.00f,MAX_DISTANCE=120.0f;
constexpr unsigned char CONFIG_VERSION=0xC1,PACKET_VERSION=0xA1;
constexpr unsigned long PACKET_LIFETIME=300;
constexpr unsigned long long KEY0=0x89A1F357C42D6B0EULL,KEY1=0x6D27B4E98350CA71ULL;
constexpr unsigned long long CONFIG_DOMAIN=0x434F4E4649475631ULL,PACKET_DOMAIN=0x5041434B45545631ULL;
static const char* COLORS[8]={"red","orange","yellow","green","cyan","blue","purple","white"};
static const char* ICONS[8]={"star","circle","diamond","triangle","moon","square","cross","skull"};
static const int DEFAULT_ICONS[8]={6,1,0,3,4,5,2,7};
static const char ALPHABET[]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

struct V3{float x,y,z;};
struct Config{int colorIndex;char color[16];char path[241];float scale,yaw;};
struct Replay{bool active;unsigned long sender,issued,nonce;unsigned long long sig;unsigned long touched;};
struct Draft{bool active;char path[241];V3 pos;float scale,yaw;};
struct Buf{unsigned char d[256];unsigned n;};

static Replay g_replay[40]={};static unsigned long g_nonce=0;static Draft g_draft={};static unsigned long g_worldToken=0;
static Lua50::CFunction g_getGuild=0,g_numRaid=0,g_numParty=0,g_partyLeader=0,g_raidOfficer=0,g_unitName=0;

static unsigned slen(const char* s){unsigned n=0;if(s)while(s[n])++n;return n;}
static char lower(char c){return c>='A'&&c<='Z'?(char)(c+32):c;}
static bool eq(const char* a,const char* b){if(!a||!b)return false;while(*a&&*b){if(*a!=*b)return false;++a;++b;}return *a==*b;}
static bool eqI(const char* a,const char* b){if(!a||!b)return false;while(*a&&*b){if(lower(*a)!=lower(*b))return false;++a;++b;}return *a==*b;}
static bool startsI(const char* s,const char* p){if(!s||!p)return false;while(*p){if(!*s||lower(*s)!=lower(*p))return false;++s;++p;}return true;}
static bool allowedGuild(const char* s){static const unsigned char e[12]={191,254,240,179,194,233,189,255,196,188,244,229};if(!s)return false;for(unsigned i=0;i<12;++i)if((unsigned char)s[i]!=(unsigned char)(e[i]^0x5A))return false;return s[12]==0;}
static void cpy(char* d,unsigned cap,const char* s){if(!cap)return;unsigned i=0;if(s)for(;s[i]&&i+1<cap;++i)d[i]=s[i];d[i]=0;}
static bool finitef(float v){union F{float f;unsigned long u;};F x={};x.f=v;return (x.u&0x7F800000UL)!=0x7F800000UL;}
static float normYaw(float v){
    if(!finitef(v))return v;bool neg=v<0.0f;float a=neg?-v:v;if(a<360.0f)return neg&&a>0.0f?360.0f-a:a;
    // fmod-equivalent reduction without CRT. Build powers of two times 360,
    // then subtract them high-to-low. Bounded for every finite float.
    float step=360.0f;while(step<=a*0.5f&&step<1.0e38f)step*=2.0f;while(step>=360.0f){if(a>=step)a-=step;step*=0.5f;}
    if(a>=360.0f)a-=360.0f;if(neg&&a>0.0f)a=360.0f-a;return a;
}
static int colorIndex(const char* s){for(int i=0;i<8;++i)if(eqI(s,COLORS[i]))return i;return -1;}
static int iconIndex(const char* s){for(int i=0;i<8;++i)if(eqI(s,ICONS[i]))return i;return -1;}

static const char* normalizePath(const char* in,char* out,unsigned cap){
    if(!in||!*in)return "MODEL_PATH_REQUIRED";unsigned n=slen(in);if(n>MAX_PATH_LEN||n+1>cap)return "MODEL_PATH_TOO_LONG";if(in[0]=='\\'||in[0]=='/')return "ABSOLUTE_MODEL_PATH";
    for(unsigned i=0;i<n;++i){unsigned char c=(unsigned char)in[i];if(c<0x20||c>0x7E){out[0]=0;return "INVALID_PATH_CHARACTER";}if(c==':'){out[0]=0;return "ABSOLUTE_MODEL_PATH";}if(c=='.'&&i+1<n&&in[i+1]=='.'){out[0]=0;return "PARENT_PATH_TRAVERSAL";}out[i]=(in[i]=='/')?'\\':in[i];}out[n]=0;
    bool m2=n>=3&&lower(out[n-3])=='.'&&lower(out[n-2])=='m'&&out[n-1]=='2';bool mdx=n>=4&&lower(out[n-4])=='.'&&lower(out[n-3])=='m'&&lower(out[n-2])=='d'&&lower(out[n-1])=='x';if(!m2&&!mdx){out[0]=0;return "UNSUPPORTED_MODEL_EXTENSION";}return "OK";
}
static const char* validateConfig(const char* color,const char* path,float scale,float yaw,Config* out){int c=colorIndex(color);if(c<0)return "UNKNOWN_COLOR";char p[241]={0};const char* r=normalizePath(path,p,sizeof(p));if(!eq(r,"OK"))return r;if(slen(p)>NETWORK_PATH_LEN)return "NETWORK_PATH_TOO_LONG";if(!finitef(scale)||scale<MIN_SCALE||scale>MAX_SCALE)return "SCALE_OUT_OF_RANGE";if(!finitef(yaw))return "YAW_NOT_FINITE";if(out){out->colorIndex=c;cpy(out->color,sizeof(out->color),COLORS[c]);cpy(out->path,sizeof(out->path),p);out->scale=scale;out->yaw=normYaw(yaw);}return "OK";}

static bool readable(const void* p,unsigned n){if(!p||!n)return false;MEMORY_BASIC_INFORMATION m={};if(VirtualQuery(p,&m,sizeof(m))!=sizeof(m)||m.State!=MEM_COMMIT)return false;DWORD q=m.Protect&0xFF;if(q==PAGE_NOACCESS||q==PAGE_EXECUTE)return false;unsigned long a=(unsigned long)p,b=(unsigned long)m.BaseAddress+(unsigned long)m.RegionSize;return a+n>=a&&a+n<=b;}
static bool executable(unsigned long a){MEMORY_BASIC_INFORMATION m={};if(VirtualQuery((void*)a,&m,sizeof(m))!=sizeof(m)||m.State!=MEM_COMMIT)return false;DWORD p=m.Protect&0xFF;return p==PAGE_EXECUTE||p==PAGE_EXECUTE_READ||p==PAGE_EXECUTE_READWRITE||p==PAGE_EXECUTE_WRITECOPY;}
using ResolveFn=void* (__fastcall*)(const char*);using PosFn=float* (__thiscall*)(void*,float*);
static bool playerPos(V3* out){if(!out)return false;void* obj=((ResolveFn)WoW112::RESOLVE_UNIT_TOKEN)("player");if(!obj||!readable(obj,4))return false;void** vt=*(void***)obj;if(!vt||!readable((unsigned char*)vt+WoW112::OFF_CGOBJECT_VTBL_GET_POSITION,4))return false;void* f=*(void**)((unsigned char*)vt+WoW112::OFF_CGOBJECT_VTBL_GET_POSITION);if(!f||!executable((unsigned long)f))return false;float t[3]={0};float* p=((PosFn)f)(obj,t);if(!p)return false;if(p!=t){if(!readable(p,12))return false;t[0]=p[0];t[1]=p[1];t[2]=p[2];}if(!finitef(t[0])||!finitef(t[1])||!finitef(t[2]))return false;out->x=t[0];out->y=t[1];out->z=t[2]+0.05f;return true;}
static bool within(const V3&a,const V3&b){float x=a.x-b.x,y=a.y-b.y,z=a.z-b.z;return x*x+y*y+z*z<=MAX_DISTANCE*MAX_DISTANCE;}

static int failure(Lua50::State L,const char* r){Lua50::PushBool(L,false);Lua50::PushString(L,r);return 2;}
static bool trustedGlobal(Lua50::State L,const char* name,Lua50::CFunction* saved){Lua50::GetGlobal(L,name);if(!Lua50::IsCFunction(L,-1))return false;Lua50::CFunction c=Lua50::ToCFunction(L,-1);if(!c||(*saved&&*saved!=c))return false;if(!*saved)*saved=c;return true;}
struct Auth{bool allowed;char guild[96];const char* reason;};
static Auth auth(Lua50::State L){
    Auth a={false,{0},"GUILD_NOT_READY"};if(!L){a.reason="AUTH_UNAVAILABLE";return a;}int old=Lua50::GetTop(L);
    // Exact old MMAuth behavior: inspect GetGuildInfo as a trusted C function,
    // but only pin the original pointer after a successful non-empty guild query.
    Lua50::GetGlobal(L,"GetGuildInfo");if(!Lua50::IsCFunction(L,-1)){Lua50::SetTop(L,old);a.reason="FUNCTION_TAMPERED";return a;}Lua50::CFunction current=Lua50::ToCFunction(L,-1);if(!current||(g_getGuild&&g_getGuild!=current)){Lua50::SetTop(L,old);a.reason="FUNCTION_TAMPERED";return a;}
    Lua50::PushString(L,"player");if(Lua50::PCall(L,1,3,0)!=0){Lua50::SetTop(L,old);a.reason="GUILD_NOT_READY";return a;}const char* g=Lua50::ToString(L,old+1);if(g)cpy(a.guild,sizeof(a.guild),g);Lua50::SetTop(L,old);if(!a.guild[0]){a.reason="GUILD_NOT_READY";return a;}if(!g_getGuild)g_getGuild=current;
    a.allowed=allowedGuild(a.guild);a.reason=a.allowed?"AUTHORIZED":"WRONG_GUILD";return a;
}
static bool callCount(Lua50::State L,const char* name,Lua50::CFunction* save,int* out){int old=Lua50::GetTop(L);if(!trustedGlobal(L,name,save)||Lua50::PCall(L,0,1,0)!=0){Lua50::SetTop(L,old);return false;}*out=(int)Lua50::ToNumber(L,old+1);Lua50::SetTop(L,old);return true;}
static bool callBool(Lua50::State L,const char* name,Lua50::CFunction* save,bool playerArg,bool* out){int old=Lua50::GetTop(L);if(!trustedGlobal(L,name,save)){Lua50::SetTop(L,old);return false;}if(playerArg)Lua50::PushString(L,"player");if(Lua50::PCall(L,playerArg?1:0,1,0)!=0){Lua50::SetTop(L,old);return false;}*out=Lua50::ToBoolean(L,old+1);Lua50::SetTop(L,old);return true;}
static bool playerName(Lua50::State L,char* out,unsigned cap){int old=Lua50::GetTop(L);if(!trustedGlobal(L,"UnitName",&g_unitName)){Lua50::SetTop(L,old);return false;}Lua50::PushString(L,"player");if(Lua50::PCall(L,1,1,0)!=0){Lua50::SetTop(L,old);return false;}const char* s=Lua50::ToString(L,old+1);cpy(out,cap,s);Lua50::SetTop(L,old);return out[0]!=0;}
static bool canSync(Lua50::State L){int raid=0,party=0;if(!callCount(L,"GetNumRaidMembers",&g_numRaid,&raid)||!callCount(L,"GetNumPartyMembers",&g_numParty,&party))return false;if(raid<=0&&party<=0)return false;bool leader=false;if(!callBool(L,"IsPartyLeader",&g_partyLeader,true,&leader))return false;if(leader)return true;if(raid>0){bool off=false;if(!callBool(L,"IsRaidOfficer",&g_raidOfficer,false,&off))return false;return off;}return false;}

static unsigned long long rol(unsigned long long x,int b){return (x<<b)|(x>>(64-b));}
static void sip(unsigned long long&v0,unsigned long long&v1,unsigned long long&v2,unsigned long long&v3){v0+=v1;v1=rol(v1,13);v1^=v0;v0=rol(v0,32);v2+=v3;v3=rol(v3,16);v3^=v2;v0+=v3;v3=rol(v3,21);v3^=v0;v2+=v1;v1=rol(v1,17);v1^=v2;v2=rol(v2,32);}
static unsigned long long rd64(const unsigned char*p){unsigned long long v=0;for(int i=0;i<8;++i)v|=((unsigned long long)p[i])<<(i*8);return v;}
static unsigned long long mac(const unsigned char*d,unsigned n,unsigned long long domain){unsigned long long v0=0x736f6d6570736575ULL^KEY0^domain,v1=0x646f72616e646f6dULL^KEY1,v2=0x6c7967656e657261ULL^KEY0,v3=0x7465646279746573ULL^KEY1^domain;unsigned at=0;while(at+8<=n){auto m=rd64(d+at);v3^=m;sip(v0,v1,v2,v3);sip(v0,v1,v2,v3);v0^=m;at+=8;}unsigned long long tail=((unsigned long long)n)<<56;for(unsigned i=0;at+i<n;++i)tail|=((unsigned long long)d[at+i])<<(i*8);v3^=tail;sip(v0,v1,v2,v3);sip(v0,v1,v2,v3);v0^=tail;v2^=0xff;for(int i=0;i<4;++i)sip(v0,v1,v2,v3);return v0^v1^v2^v3;}
static bool put8(Buf&b,unsigned v){if(b.n+1>sizeof(b.d))return false;b.d[b.n++]=(unsigned char)v;return true;}static bool put16(Buf&b,unsigned v){return put8(b,v)&&put8(b,v>>8);}static bool put32(Buf&b,unsigned long v){for(int i=0;i<4;++i)if(!put8(b,v>>(8*i)))return false;return true;}static bool put64(Buf&b,unsigned long long v){for(int i=0;i<8;++i)if(!put8(b,(unsigned)(v>>(8*i))))return false;return true;}static bool putBytes(Buf&b,const char*s,unsigned n){if(b.n+n>sizeof(b.d))return false;for(unsigned i=0;i<n;++i)b.d[b.n++]=(unsigned char)s[i];return true;}
static bool take8(const Buf&b,unsigned&at,unsigned*o){if(at+1>b.n)return false;*o=b.d[at++];return true;}static bool take16(const Buf&b,unsigned&at,unsigned*o){unsigned a=0,c=0;if(!take8(b,at,&a)||!take8(b,at,&c))return false;*o=a|(c<<8);return true;}static bool take32(const Buf&b,unsigned&at,unsigned long*o){if(at+4>b.n)return false;unsigned long v=0;for(int i=0;i<4;++i)v|=((unsigned long)b.d[at+i])<<(8*i);at+=4;*o=v;return true;}static bool take64(const Buf&b,unsigned&at,unsigned long long*o){if(at+8>b.n)return false;*o=rd64(b.d+at);at+=8;return true;}
static bool b64enc(const Buf&b,char*out,unsigned cap){unsigned acc=0;int bits=0,j=0;for(unsigned i=0;i<b.n;++i){acc=(acc<<8)|b.d[i];bits+=8;while(bits>=6){bits-=6;if((unsigned)j+1>=cap)return false;out[j++]=ALPHABET[(acc>>bits)&63];}}if(bits>0){if((unsigned)j+1>=cap)return false;out[j++]=ALPHABET[(acc<<(6-bits))&63];}out[j]=0;return true;}
static int b64char(char c){if(c>='A'&&c<='Z')return c-'A';if(c>='a'&&c<='z')return c-'a'+26;if(c>='0'&&c<='9')return c-'0'+52;if(c=='-')return 62;if(c=='_')return 63;return -1;}
static bool b64dec(const char*s,Buf&b){b.n=0;unsigned n=slen(s);if(!n||n>252)return false;unsigned acc=0;int bits=0;for(unsigned i=0;i<n;++i){int v=b64char(s[i]);if(v<0)return false;acc=(acc<<6)|(unsigned)v;bits+=6;if(bits>=8){bits-=8;if(b.n>=sizeof(b.d))return false;b.d[b.n++]=(unsigned char)((acc>>bits)&255);}}return true;}
static unsigned long nameHash(const char*s){unsigned long h=2166136261UL;for(unsigned i=0;s&&s[i]&&s[i]!='-';++i){h^=(unsigned char)lower(s[i]);h*=16777619UL;}return h;}
static long quant(float v){double s=(double)v*100.0;if(s>2147483647.0)return 2147483647L;if(s<-2147483648.0)return (long)0x80000000UL;return (long)(s>=0.0?s+0.5:s-0.5);}
static unsigned long epochNow(){SYSTEMTIME t={0};GetSystemTime(&t);auto leap=[](unsigned y){return (y%4==0&&y%100!=0)||y%400==0;};static const unsigned md[12]={31,28,31,30,31,30,31,31,30,31,30,31};unsigned long days=0;for(unsigned y=1970;y<t.wYear;++y)days+=leap(y)?366:365;for(unsigned m=1;m<t.wMonth;++m){days+=md[m-1];if(m==2&&leap(t.wYear))days++;}days+=t.wDay-1;return days*86400UL+t.wHour*3600UL+t.wMinute*60UL+t.wSecond;}
static bool remember(unsigned long sender,unsigned long issued,unsigned long nonce,unsigned long long sig){Replay* empty=0,*oldest=0;for(auto&s:g_replay){if(s.active&&s.sender==sender&&s.issued==issued&&s.nonce==nonce&&s.sig==sig)return false;if(!s.active&&!empty)empty=&s;if(s.active&&(!oldest||(long)(s.touched-oldest->touched)<0))oldest=&s;}Replay*c=empty?empty:oldest;if(!c)return false;c->active=true;c->sender=sender;c->issued=issued;c->nonce=nonce;c->sig=sig;c->touched=GetTickCount();return true;}

static bool seal(const char* color,const char* path,float scale,float yaw,char* token,unsigned tokenCap,Config* cfg,const char** reason){Config c={};const char*r=validateConfig(color,path,scale,yaw,&c);if(!eq(r,"OK")){*reason=r;return false;}Buf b={};put8(b,CONFIG_VERSION);put8(b,c.colorIndex);put16(b,(unsigned)(c.scale*1000.0f+0.5f));put16(b,(unsigned)(c.yaw*10.0f+0.5f));unsigned pn=slen(c.path);put8(b,pn);putBytes(b,c.path,pn);put64(b,mac(b.d,b.n,CONFIG_DOMAIN));if(!b64enc(b,token,tokenCap)){*reason="TOKEN_TOO_LONG";return false;}if(cfg)*cfg=c;*reason="OK";return true;}
static bool openConfig(const char* expected,const char* token,Config* cfg,const char** reason){Buf b={};if(!b64dec(token,b)||b.n<15){*reason="TOKEN_INVALID";return false;}unsigned signedN=b.n-8;unsigned at=signedN;unsigned long long supplied=0;if(!take64(b,at,&supplied)||supplied!=mac(b.d,signedN,CONFIG_DOMAIN)){*reason="TOKEN_SIGNATURE_INVALID";return false;}at=0;unsigned ver=0,col=0,sc=0,yaw=0,pn=0;if(!take8(b,at,&ver)||ver!=CONFIG_VERSION||!take8(b,at,&col)||col>=8||!take16(b,at,&sc)||!take16(b,at,&yaw)||!take8(b,at,&pn)||at+pn!=signedN){*reason="TOKEN_FORMAT_INVALID";return false;}char path[241]={0};if(pn>=sizeof(path)){*reason="TOKEN_FORMAT_INVALID";return false;}for(unsigned i=0;i<pn;++i)path[i]=(char)b.d[at+i];Config c={};const char*r=validateConfig(COLORS[col],path,(float)sc/1000.0f,(float)yaw/10.0f,&c);if(!eq(r,"OK")){*reason=r;return false;}if(colorIndex(expected)!=c.colorIndex){*reason="TOKEN_COLOR_MISMATCH";return false;}*cfg=c;*reason="OK";return true;}
static bool buildPacket(const Config&cfg,const char* icon,const V3&p,const char* sender,char*out,unsigned cap,const char**reason){int ic=iconIndex(icon);if(cfg.colorIndex<0||cfg.colorIndex>=8||ic<0||!sender||!*sender||!finitef(p.x)||!finitef(p.y)||!finitef(p.z)){*reason="PACKET_ARGUMENTS_INVALID";return false;}Config c={};const char*r=validateConfig(cfg.color,cfg.path,cfg.scale,cfg.yaw,&c);if(!eq(r,"OK")){*reason=r;return false;}Buf b={};unsigned long issued=epochNow(),nonce=++g_nonce;put8(b,PACKET_VERSION);put8(b,c.colorIndex);put8(b,ic);put32(b,(unsigned long)quant(p.x));put32(b,(unsigned long)quant(p.y));put32(b,(unsigned long)quant(p.z));put16(b,(unsigned)(c.scale*1000.0f+0.5f));put16(b,(unsigned)(c.yaw*10.0f+0.5f));put32(b,issued);put32(b,nonce);put32(b,nameHash(sender));unsigned pn=slen(c.path);put8(b,pn);putBytes(b,c.path,pn);put64(b,mac(b.d,b.n,PACKET_DOMAIN));if(!b64enc(b,out,cap)||slen(out)>245){out[0]=0;*reason="PACKET_TOO_LONG";return false;}*reason="OK";return true;}
static bool openPacket(const char*packet,const char*sender,Config*cfg,char*icon,unsigned iconCap,V3*pos,const char**reason){Buf b={};if(!b64dec(packet,b)||b.n<36){*reason="PACKET_INVALID";return false;}unsigned signedN=b.n-8,at=signedN;unsigned long long supplied=0;if(!take64(b,at,&supplied)||supplied!=mac(b.d,signedN,PACKET_DOMAIN)){*reason="PACKET_SIGNATURE_INVALID";return false;}at=0;unsigned ver=0,col=0,ic=0,sc=0,yaw=0,pn=0;unsigned long x=0,y=0,z=0,issued=0,nonce=0,sh=0;if(!take8(b,at,&ver)||ver!=PACKET_VERSION||!take8(b,at,&col)||col>=8||!take8(b,at,&ic)||ic>=8||!take32(b,at,&x)||!take32(b,at,&y)||!take32(b,at,&z)||!take16(b,at,&sc)||!take16(b,at,&yaw)||!take32(b,at,&issued)||!take32(b,at,&nonce)||!take32(b,at,&sh)||!take8(b,at,&pn)||at+pn!=signedN){*reason="PACKET_FORMAT_INVALID";return false;}if(!sender||!*sender||sh!=nameHash(sender)){*reason="PACKET_SENDER_MISMATCH";return false;}unsigned long now=epochNow(),age=now>=issued?now-issued:issued-now;if(age>PACKET_LIFETIME){*reason="PACKET_EXPIRED";return false;}char path[241]={0};if(pn>=sizeof(path)){*reason="PACKET_FORMAT_INVALID";return false;}for(unsigned i=0;i<pn;++i)path[i]=(char)b.d[at+i];Config c={};const char*r=validateConfig(COLORS[col],path,(float)sc/1000.0f,(float)yaw/10.0f,&c);if(!eq(r,"OK")){*reason=r;return false;}V3 p={(float)(long)x/100.0f,(float)(long)y/100.0f,(float)(long)z/100.0f};if(!finitef(p.x)||!finitef(p.y)||!finitef(p.z)){*reason="PACKET_POSITION_INVALID";return false;}if(!remember(sh,issued,nonce,supplied)){*reason="PACKET_REPLAYED";return false;}*cfg=c;cpy(icon,iconCap,ICONS[ic]);*pos=p;*reason="OK";return true;}

static int pushAuth(Lua50::State L){Auth a=auth(L);Lua50::PushBool(L,a.allowed);if(a.guild[0])Lua50::PushString(L,a.guild);else Lua50::PushNil(L);Lua50::PushString(L,a.reason);return 3;}
static int previewAt(Lua50::State L,const char* path,V3 p,float scale,float yaw){V3 actor={};if(!playerPos(&actor))return failure(L,"PLAYER_POSITION_UNAVAILABLE");char norm[241]={0};const char*r=normalizePath(path,norm,sizeof(norm));if(!eq(r,"OK"))return failure(L,r);if(!finitef(p.x)||!finitef(p.y)||!finitef(p.z))return failure(L,"POSITION_NOT_FINITE");if(!finitef(scale))return failure(L,"SCALE_NOT_FINITE");if(scale<MIN_SCALE||scale>MAX_SCALE)return failure(L,"SCALE_OUT_OF_RANGE");if(!finitef(yaw))return failure(L,"YAW_NOT_FINITE");yaw=normYaw(yaw);if(!within(p,actor))return failure(L,"DISTANCE_EXCEEDED");char rendererPath[241]={0};if(!TysVisual::moonAdvancedPreviewSet(norm,p.x,p.y,p.z,scale,yaw,rendererPath,sizeof(rendererPath)))return failure(L,TysVisual::lastError());Auth second=auth(L);if(!second.allowed){TysVisual::moonAdvancedPreviewClear();return failure(L,"ACCESS_DENIED");}g_draft.active=true;cpy(g_draft.path,sizeof(g_draft.path),rendererPath);g_draft.pos=p;g_draft.scale=scale;g_draft.yaw=yaw;Lua50::PushBool(L,true);Lua50::PushNumber(L,p.x);Lua50::PushNumber(L,p.y);Lua50::PushNumber(L,p.z+0.05f);Lua50::PushString(L,rendererPath);return 5;}
static int placeMain(Lua50::State L,const char* color,const char* icon,V3 p,const char* token){Config c={};const char*r=0;if(!openConfig(color,token,&c,&r))return failure(L,r);if(!finitef(p.x)||!finitef(p.y)||!finitef(p.z))return failure(L,"MARKER_RECORD_FAILED");V3 actor={};if(!playerPos(&actor))return failure(L,"PLAYER_POSITION_UNAVAILABLE");if(!within(p,actor))return failure(L,"DISTANCE_EXCEEDED");char packet[256]={0};if(canSync(L)){char sender[96]={0};if(!playerName(L,sender,sizeof(sender)))return failure(L,"PLAYER_NAME_UNAVAILABLE");if(!buildPacket(c,icon,p,sender,packet,sizeof(packet),&r))return failure(L,r);}char np[241]={0},nc[16]={0},ni[16]={0};if(!TysVisual::moonSetCustom(c.color,icon,p.x,p.y,p.z,c.path,c.scale,c.yaw,np,sizeof(np),nc,sizeof(nc),ni,sizeof(ni)))return failure(L,TysVisual::lastError());Lua50::PushBool(L,true);Lua50::PushNumber(L,p.x);Lua50::PushNumber(L,p.y);Lua50::PushNumber(L,p.z);Lua50::PushString(L,nc);Lua50::PushString(L,ni);if(packet[0])Lua50::PushString(L,packet);else Lua50::PushNil(L);Lua50::PushString(L,np);return 8;}

} // namespace

int dispatch(Lua50::State L,const char* cmd,bool visualEnabled){
    if(!cmd)return -1;if(eqI(cmd,"MMAuth"))return pushAuth(L);
    if(eqI(cmd,"MoonMarker.Main.Remote")){if(!visualEnabled)return failure(L,"FEATURE_DISABLED");if(Lua50::GetTop(L)<3||!Lua50::IsString(L,2)||!Lua50::IsString(L,3))return failure(L,"REMOTE_PACKET_REQUIRED");Config c={};char icon[16]={0};V3 p={};const char*r=0;if(!openPacket(Lua50::ToString(L,2),Lua50::ToString(L,3),&c,icon,sizeof(icon),&p,&r))return failure(L,r);char np[241]={0},nc[16]={0},ni[16]={0};if(!TysVisual::moonSetCustom(c.color,icon,p.x,p.y,p.z,c.path,c.scale,c.yaw,np,sizeof(np),nc,sizeof(nc),ni,sizeof(ni)))return failure(L,TysVisual::lastError());Lua50::PushBool(L,true);Lua50::PushString(L,nc);Lua50::PushString(L,ni);Lua50::PushString(L,np);Lua50::PushNumber(L,p.x);Lua50::PushNumber(L,p.y);Lua50::PushNumber(L,p.z);return 7;}
    if(!startsI(cmd,"MoonMarker.Advanced."))return -1;Auth a=auth(L);if(!a.allowed)return failure(L,"ACCESS_DENIED");
    if(eqI(cmd,"MoonMarker.Advanced.Ping")){Lua50::PushBool(L,true);Lua50::PushString(L,"AUTHORIZED");return 2;}
    int scan=TysScanMedia::dispatchMoonAdvanced(L,cmd);if(scan>=0)return scan;
    if(eqI(cmd,"MoonMarker.Advanced.PreviewAt")){if(!visualEnabled)return failure(L,"FEATURE_DISABLED");if(Lua50::GetTop(L)<5||!Lua50::IsString(L,2)||!Lua50::IsNumber(L,3)||!Lua50::IsNumber(L,4)||!Lua50::IsNumber(L,5))return failure(L,"PREVIEW_ARGUMENTS_REQUIRED");float sc=Lua50::GetTop(L)>=6&&Lua50::IsNumber(L,6)?(float)Lua50::ToNumber(L,6):1.0f,y=Lua50::GetTop(L)>=7&&Lua50::IsNumber(L,7)?(float)Lua50::ToNumber(L,7):0.0f;V3 p={(float)Lua50::ToNumber(L,3),(float)Lua50::ToNumber(L,4),(float)Lua50::ToNumber(L,5)};return previewAt(L,Lua50::ToString(L,2),p,sc,y);}
    if(eqI(cmd,"MoonMarker.Advanced.PreviewAtPlayer")){if(!visualEnabled)return failure(L,"FEATURE_DISABLED");if(Lua50::GetTop(L)<2||!Lua50::IsString(L,2))return failure(L,"MODEL_PATH_REQUIRED");V3 p={};if(!playerPos(&p))return failure(L,"PLAYER_POSITION_UNAVAILABLE");p.z-=0.05f;float sc=Lua50::GetTop(L)>=3&&Lua50::IsNumber(L,3)?(float)Lua50::ToNumber(L,3):1.0f,y=Lua50::GetTop(L)>=4&&Lua50::IsNumber(L,4)?(float)Lua50::ToNumber(L,4):0.0f;return previewAt(L,Lua50::ToString(L,2),p,sc,y);}
    if(eqI(cmd,"MoonMarker.Advanced.ClearPreview")){TysVisual::moonAdvancedPreviewClear();g_draft={};Lua50::PushBool(L,true);Lua50::PushString(L,"CLEARED");return 2;}
    if(eqI(cmd,"MoonMarker.Advanced.SetPreviewTransform")){if(!visualEnabled)return failure(L,"FEATURE_DISABLED");if(Lua50::GetTop(L)<3||!Lua50::IsNumber(L,2)||!Lua50::IsNumber(L,3))return failure(L,"TRANSFORM_REQUIRED");if(!g_draft.active)return failure(L,"LOCAL_DRAFT_NOT_FOUND");float sc=(float)Lua50::ToNumber(L,2),y=(float)Lua50::ToNumber(L,3);if(!finitef(sc))return failure(L,"SCALE_NOT_FINITE");if(sc<MIN_SCALE||sc>MAX_SCALE)return failure(L,"SCALE_OUT_OF_RANGE");if(!finitef(y))return failure(L,"YAW_NOT_FINITE");y=normYaw(y);V3 actor={};if(!playerPos(&actor))return failure(L,"PLAYER_POSITION_UNAVAILABLE");if(!within(g_draft.pos,actor))return failure(L,"DISTANCE_EXCEEDED");if(!TysVisual::moonAdvancedPreviewTransform(sc,y))return failure(L,"TRANSFORM_REJECTED");Auth second=auth(L);if(!second.allowed)return failure(L,"ACCESS_DENIED");g_draft.scale=sc;g_draft.yaw=y;Lua50::PushBool(L,true);Lua50::PushNumber(L,sc);Lua50::PushNumber(L,y);return 3;}
    if(eqI(cmd,"MoonMarker.Advanced.PreviewStatus")){bool active=false,ready=false;char p[241]={0};float sc=1,y=0;TysVisual::moonAdvancedPreviewStatus(&active,&ready,p,sizeof(p),&sc,&y);Lua50::PushBool(L,active);Lua50::PushBool(L,ready);Lua50::PushString(L,p);Lua50::PushNumber(L,sc);Lua50::PushNumber(L,y);Lua50::PushString(L,TysVisual::lastError());return 6;}
    if(eqI(cmd,"MoonMarker.Advanced.Main.Seal")){if(Lua50::GetTop(L)<2||!Lua50::IsString(L,2))return failure(L,"COLOR_REQUIRED");if(!g_draft.active)return failure(L,"LOCAL_DRAFT_NOT_FOUND");char tok[256]={0};Config c={};const char*r=0;if(!seal(Lua50::ToString(L,2),g_draft.path,g_draft.scale,g_draft.yaw,tok,sizeof(tok),&c,&r))return failure(L,r);Lua50::PushBool(L,true);Lua50::PushString(L,tok);Lua50::PushString(L,c.path);Lua50::PushNumber(L,c.scale);Lua50::PushNumber(L,c.yaw);return 5;}
    if(eqI(cmd,"MoonMarker.Advanced.Main.Validate")){if(Lua50::GetTop(L)<3||!Lua50::IsString(L,2)||!Lua50::IsString(L,3))return failure(L,"TOKEN_REQUIRED");Config c={};const char*r=0;if(!openConfig(Lua50::ToString(L,2),Lua50::ToString(L,3),&c,&r))return failure(L,r);Lua50::PushBool(L,true);Lua50::PushString(L,c.path);Lua50::PushNumber(L,c.scale);Lua50::PushNumber(L,c.yaw);return 4;}
    if(eqI(cmd,"MoonMarker.Advanced.Main.PlaceAt")){if(!visualEnabled)return failure(L,"FEATURE_DISABLED");if(Lua50::GetTop(L)<7||!Lua50::IsString(L,2)||!Lua50::IsString(L,3)||!Lua50::IsNumber(L,4)||!Lua50::IsNumber(L,5)||!Lua50::IsNumber(L,6)||!Lua50::IsString(L,7))return failure(L,"PLACE_ARGUMENTS_REQUIRED");V3 p={(float)Lua50::ToNumber(L,4),(float)Lua50::ToNumber(L,5),(float)Lua50::ToNumber(L,6)};return placeMain(L,Lua50::ToString(L,2),Lua50::ToString(L,3),p,Lua50::ToString(L,7));}
    return failure(L,"NOT_IMPLEMENTED");
}

void onWorldLeaving(){g_draft={};TysVisual::moonAdvancedPreviewClear();}
void observeWorldContext(unsigned long token){if(token!=g_worldToken){g_worldToken=token;g_draft={};}}
void clearLocalDraft(){g_draft={};}
void shutdown(){g_draft={};for(auto&r:g_replay)r={};g_nonce=0;g_worldToken=0;g_getGuild=g_numRaid=g_numParty=g_partyLeader=g_raidOfficer=g_unitName=0;}

} // namespace TysMoonAdvanced
