#include <windows.h>
#include "unit_state_core.h"
#include "native_bus.h"
#include "wow112_offsets.h"
#include "custom_event_bridge.h"
#include "unit_state_descriptor_layout.h"
#include "unit_state_lifecycle.h"

namespace TysUnitStateCore { namespace {
constexpr unsigned MAX_TRACKED=128;
constexpr unsigned long FAST_GUID_LOOKUP=0x00464870u;
constexpr unsigned long UNIT_GUID_FN=0x00515970u;
constexpr unsigned long OBJECT_TYPE_UNIT=3u,OBJECT_TYPE_PLAYER=4u,MAX_POWER_TYPE=4u;
struct Entry{unsigned long long guid;unsigned long health,maxHealth,power,maxPower,powerType,combatFlag,capturedAtMs;bool dead,used,valid,dirty,powerValid;};
static Entry g_entries[MAX_TRACKED]={};
static volatile LONG g_init=0,g_inSub=0,g_tickSub=0;
static volatile LONG g_updatePackets=0,g_compressedUpdatePackets=0,g_dirtySignals=0,g_coalescedSignals=0,g_reconcilePasses=0,g_recordsChecked=0,g_objectUnavailable=0,g_descriptorFailures=0;
static volatile LONG g_healthEvents=0,g_powerEvents=0,g_combatEvents=0,g_trackCalls=0,g_untrackCalls=0,g_capacityFailures=0;
static unsigned long long g_lastChangedGuid=0;static unsigned long g_lastChangedMask=0;static unsigned long g_worldGeneration=1;static char g_status[96]="LAZY_NOT_SUBSCRIBED";
static void setStr(Lua50::State L,const char*k,const char*v){Lua50::PushString(L,k);Lua50::PushString(L,v?v:"");Lua50::SetTable(L,-3);}static void setNum(Lua50::State L,const char*k,double v){Lua50::PushString(L,k);Lua50::PushNumber(L,v);Lua50::SetTable(L,-3);}static void setBool(Lua50::State L,const char*k,bool v){Lua50::PushString(L,k);Lua50::PushBool(L,v);Lua50::SetTable(L,-3);}static void setNil(Lua50::State L,const char*k){Lua50::PushString(L,k);Lua50::PushNil(L);Lua50::SetTable(L,-3);}
static bool readableProtection(DWORD p){p&=0xffu;return p==PAGE_READONLY||p==PAGE_READWRITE||p==PAGE_WRITECOPY||p==PAGE_EXECUTE_READ||p==PAGE_EXECUTE_READWRITE||p==PAGE_EXECUTE_WRITECOPY;}static bool canRead(unsigned long a,unsigned long n){if(!a||!n)return false;MEMORY_BASIC_INFORMATION m={};if(VirtualQuery((const void*)a,&m,sizeof(m))!=sizeof(m))return false;if(m.State!=MEM_COMMIT||(m.Protect&(PAGE_GUARD|PAGE_NOACCESS))||!readableProtection(m.Protect))return false;unsigned long b=(unsigned long)m.BaseAddress,e=b+(unsigned long)m.RegionSize;return a>=b&&a<=e&&n<=e-a;}static bool executable(unsigned long a){if(!a)return false;MEMORY_BASIC_INFORMATION m={};if(VirtualQuery((const void*)a,&m,sizeof(m))!=sizeof(m)||m.State!=MEM_COMMIT||(m.Protect&(PAGE_GUARD|PAGE_NOACCESS)))return false;DWORD p=m.Protect&0xffu;return p==PAGE_EXECUTE||p==PAGE_EXECUTE_READ||p==PAGE_EXECUTE_READWRITE||p==PAGE_EXECUTE_WRITECOPY;}
static bool hexNibble(char c,unsigned*o){if(c>='0'&&c<='9'){*o=(unsigned)(c-'0');return true;}if(c>='a'&&c<='f'){*o=(unsigned)(c-'a'+10);return true;}if(c>='A'&&c<='F'){*o=(unsigned)(c-'A'+10);return true;}return false;}static bool parseGuidText(const char*s,unsigned long long*out){if(!s||!out)return false;*out=0;while(*s==' '||*s=='\t'||*s=='\r'||*s=='\n')++s;if(s[0]=='0'&&(s[1]=='x'||s[1]=='X'))s+=2;unsigned long long v=0;unsigned d=0;for(;*s&&d<16;++s,++d){unsigned n=0;if(!hexNibble(*s,&n))return false;v=(v<<4)|n;}if(*s||!d||!v)return false;*out=v;return true;}
static bool resolveGuid(Lua50::State L,int idx,unsigned long long*out){if(!out)return false;*out=0;if(Lua50::IsNumber(L,idx)){double n=Lua50::ToNumber(L,idx);if(n<=0)return false;*out=(unsigned long long)n;return *out!=0;}if(!Lua50::IsString(L,idx))return false;const char*s=Lua50::ToString(L,idx);if(!s||!*s)return false;if(executable(UNIT_GUID_FN)){using Fn=unsigned long long(__fastcall*)(const char*);unsigned long long g=((Fn)UNIT_GUID_FN)(s);if(g){*out=g;return true;}}return parseGuidText(s,out);}
static void formatGuid(char*b,unsigned long n,unsigned long long g){if(!b||n<19)return;static const char h[]="0123456789ABCDEF";b[0]='0';b[1]='x';for(unsigned i=0;i<16;++i){unsigned shift=(15u-i)*4u;b[2+i]=h[(unsigned)((g>>shift)&0xFu)];}b[18]=0;}
static void pushGuid(Lua50::State L,const char*k,unsigned long long g){char b[24]={};formatGuid(b,sizeof(b),g);setStr(L,k,b);}static Entry* find(unsigned long long g){for(unsigned i=0;i<MAX_TRACKED;++i)if(g_entries[i].used&&g_entries[i].guid==g)return &g_entries[i];return 0;}static unsigned trackedCount(){unsigned n=0;for(unsigned i=0;i<MAX_TRACKED;++i)if(g_entries[i].used)++n;return n;}static bool pending(){for(unsigned i=0;i<MAX_TRACKED;++i)if(g_entries[i].used&&g_entries[i].dirty)return true;return false;}
static Entry* track(unsigned long long g,bool*isNew){if(isNew)*isNew=false;Entry*e=find(g);if(e)return e;for(unsigned i=0;i<MAX_TRACKED;++i)if(!g_entries[i].used){g_entries[i]=Entry{};g_entries[i].used=true;g_entries[i].dirty=true;g_entries[i].guid=g;if(isNew)*isNew=true;return &g_entries[i];}return 0;}
static void markDirtyAll(){for(unsigned i=0;i<MAX_TRACKED;++i)if(g_entries[i].used){if(g_entries[i].dirty)++g_coalescedSignals;else{g_entries[i].dirty=true;++g_dirtySignals;}}}
static void onIncoming(unsigned long op,TysNativeBus::CDataStoreView*){if(op==WoW112::SMSG_UPDATE_OBJECT_OPCODE){++g_updatePackets;markDirtyAll();}else if(op==WoW112::SMSG_COMPRESSED_UPDATE_OBJECT_OPCODE){++g_compressedUpdatePackets;markDirtyAll();}}
static bool resolveObject(unsigned long long guid,unsigned long*out){if(!guid||!out||!executable(FAST_GUID_LOOKUP))return false;using Fn=unsigned long(__fastcall*)(unsigned long long);unsigned long obj=((Fn)FAST_GUID_LOOKUP)(guid);if(!obj||(obj&1u)||!canRead(obj,TysUnitStateLayout::OBJECT_VALIDATE_BYTES))return false;unsigned long type=*(const unsigned long*)(obj+TysUnitStateLayout::OBJECT_TYPE);if(type!=OBJECT_TYPE_UNIT&&type!=OBJECT_TYPE_PLAYER)return false;unsigned long long live=*(const unsigned long long*)(obj+TysUnitStateLayout::OBJECT_GUID_LOW);if(live!=guid)return false;*out=obj;return true;}
static bool reconcileEntry(Entry&e){++g_recordsChecked;unsigned long obj=0;if(!resolveObject(e.guid,&obj)){++g_objectUnavailable;e.valid=false;e.powerValid=false;e.dead=false;e.combatFlag=0;e.dirty=false;return false;}unsigned long desc=*(const unsigned long*)(obj+TysUnitStateLayout::OBJECT_DESCRIPTOR_PTR);if(!desc||(desc&3u)||!canRead(desc+TysUnitStateLayout::DESC_RANGE_START,TysUnitStateLayout::DESC_RANGE_BYTES)){++g_descriptorFailures;e.dirty=false;return e.valid;}unsigned long health=*(const unsigned long*)(desc+TysUnitStateLayout::DESC_HEALTH),maxHealth=*(const unsigned long*)(desc+TysUnitStateLayout::DESC_MAX_HEALTH),flags=*(const unsigned long*)(desc+TysUnitStateLayout::DESC_UNIT_FLAGS),dyn=*(const unsigned long*)(desc+TysUnitStateLayout::DESC_DYNAMIC_FLAGS),packed=*(const unsigned long*)(desc+TysUnitStateLayout::DESC_POWER_TYPE_PACKED),pt=TysUnitStateLayout::powerTypeFromPacked(packed);if(pt>MAX_POWER_TYPE){++g_descriptorFailures;e.dirty=false;return e.valid;}unsigned long power=*(const unsigned long*)(desc+TysUnitStateLayout::powerOffset(pt)),maxPower=*(const unsigned long*)(desc+TysUnitStateLayout::maxPowerOffset(pt));bool combat=TysUnitStateLayout::inCombat(flags),dead=TysUnitStateLayout::dead(health,dyn);bool had=e.valid,hadPower=e.powerValid;unsigned long oh=e.health,omh=e.maxHealth,oc=e.combatFlag,opt=e.powerType,op=e.power,omp=e.maxPower;bool od=e.dead;e.health=health;e.maxHealth=maxHealth;e.dead=dead;e.combatFlag=combat?1u:0u;e.powerType=pt;e.power=power;e.maxPower=maxPower;e.powerValid=true;e.capturedAtMs=GetTickCount();e.valid=true;e.dirty=false;unsigned long cm=0;if(had&&(oh!=e.health||omh!=e.maxHealth||od!=e.dead)){if(TysCustomEvents::emitUnitHealth(e.guid,oh,e.health,e.maxHealth,e.dead))++g_healthEvents;cm|=TysUnitStateLifecycle::CHANGE_HEALTH;}if(had&&hadPower){unsigned long pm=0;if(opt!=e.powerType)pm|=TysUnitStateLayout::POWER_TYPE_CHANGED;if(op!=e.power)pm|=TysUnitStateLayout::POWER_VALUE_CHANGED;if(omp!=e.maxPower)pm|=TysUnitStateLayout::POWER_MAX_CHANGED;if(pm){if(TysCustomEvents::emitUnitPower(e.guid,e.powerType,op,e.power,e.maxPower,pm))++g_powerEvents;cm|=TysUnitStateLifecycle::CHANGE_POWER;}}if(had&&oc!=e.combatFlag){if(TysCustomEvents::emitUnitCombat(e.guid,oc!=0,e.combatFlag!=0))++g_combatEvents;cm|=TysUnitStateLifecycle::CHANGE_COMBAT;}if(cm){g_lastChangedGuid=e.guid;g_lastChangedMask=cm;}return true;}
static void onTick(){if(!pending())return;++g_reconcilePasses;for(unsigned i=0;i<MAX_TRACKED;++i)if(g_entries[i].used&&g_entries[i].dirty)reconcileEntry(g_entries[i]);}
static int pushEntry(Lua50::State L,const Entry&e){Lua50::NewTable(L);pushGuid(L,"guid",e.guid);setNum(L,"guidLow",(unsigned long)e.guid);setNum(L,"guidHigh",(unsigned long)(e.guid>>32));setBool(L,"tracked",e.used);setBool(L,"visible",e.valid);setBool(L,"valid",e.valid);setBool(L,"dirty",e.dirty);setNum(L,"health",e.health);setNum(L,"maxHealth",e.maxHealth);setBool(L,"dead",e.valid&&e.dead);setBool(L,"combat",e.combatFlag!=0);if(e.powerValid){setNum(L,"powerType",e.powerType);setNum(L,"power",e.power);setNum(L,"maxPower",e.maxPower);}else{setNil(L,"powerType");setNil(L,"power");setNil(L,"maxPower");}setNum(L,"capturedAtMs",e.capturedAtMs);return 1;}
}

bool initialize(){if(InterlockedCompareExchange(&g_init,1,0)!=0)return g_inSub&&g_tickSub;bool a=TysNativeBus::subscribeIncoming(&onIncoming),b=TysNativeBus::subscribeWorldTick(&onTick);InterlockedExchange(&g_inSub,a?1:0);InterlockedExchange(&g_tickSub,b?1:0);TysCustomEvents::ensureUnitStateEvents();const char*s=(a&&b)?"READY_UNITSTATE_US1R2":"LAZY_NOT_SUBSCRIBED";unsigned i=0;for(;s[i]&&i+1<sizeof(g_status);++i)g_status[i]=s[i];g_status[i]=0;return a&&b;}
const char* status(){return g_status;}unsigned long worldGeneration(){return g_worldGeneration;}
void onWorldLeaving(){for(unsigned i=0;i<MAX_TRACKED;++i){Entry&e=g_entries[i];if(!e.used)continue;e.health=e.maxHealth=e.power=e.maxPower=e.powerType=e.combatFlag=e.capturedAtMs=0;e.dead=false;e.valid=false;e.dirty=false;e.powerValid=false;}g_lastChangedGuid=0;g_lastChangedMask=0;g_worldGeneration=TysUnitStateLifecycle::nextNonZeroGeneration(g_worldGeneration);}
int dispatchStatus(Lua50::State L){initialize();Lua50::NewTable(L);setStr(L,"status",g_status);setStr(L,"architecture","LAZY_TRACKED_GUIDS_UPDATEOBJECT_DIRTY_RECONCILE");setStr(L,"authority","CLIENT_UNIT_DESCRIPTOR_AFTER_STOCK_HANDLER");setNum(L,"capacity",MAX_TRACKED);setNum(L,"tracked",trackedCount());setBool(L,"customEventsReady",TysCustomEvents::ensureUnitStateEvents());setBool(L,"dynamicEventSlots",true);setNum(L,"eventHealthSlot",TysCustomEvents::unitHealthSlot());setNum(L,"eventPowerSlot",TysCustomEvents::unitPowerSlot());setNum(L,"eventCombatSlot",TysCustomEvents::unitCombatSlot());setNum(L,"updateObjectOpcode",WoW112::SMSG_UPDATE_OBJECT_OPCODE);setNum(L,"compressedUpdateObjectOpcode",WoW112::SMSG_COMPRESSED_UPDATE_OBJECT_OPCODE);setNum(L,"fastGuidLookupAddress",FAST_GUID_LOOKUP);setNum(L,"updatePackets",g_updatePackets);setNum(L,"compressedUpdatePackets",g_compressedUpdatePackets);setNum(L,"dirtySignals",g_dirtySignals);setNum(L,"coalescedSignals",g_coalescedSignals);setNum(L,"reconcilePasses",g_reconcilePasses);setNum(L,"recordsChecked",g_recordsChecked);setNum(L,"objectUnavailable",g_objectUnavailable);setNum(L,"descriptorFailures",g_descriptorFailures);setNum(L,"healthEvents",g_healthEvents);setNum(L,"powerEvents",g_powerEvents);setNum(L,"combatEvents",g_combatEvents);setNum(L,"trackCalls",g_trackCalls);setNum(L,"untrackCalls",g_untrackCalls);setNum(L,"capacityFailures",g_capacityFailures);if(g_lastChangedGuid)pushGuid(L,"lastChangedGuid",g_lastChangedGuid);else setNil(L,"lastChangedGuid");setNum(L,"lastChangedMask",g_lastChangedMask);setNum(L,"worldGeneration",g_worldGeneration);setBool(L,"reconcilePending",pending());setBool(L,"directHook",false);setBool(L,"objectManagerPolling",false);setBool(L,"packetBodyParsing",false);setBool(L,"zlibDecompression",false);setBool(L,"timer",false);setBool(L,"idleTickPath",true);setStr(L,"powerSemantics","ACTIVE_POWER_ONLY_TYPE_VALUE_MAX");setStr(L,"powerMaskSemantics","BIT0_TYPE_BIT1_VALUE_BIT2_MAX");setStr(L,"descriptorReadPolicy","ONE_OBJECT_RANGE_PLUS_ONE_DESCRIPTOR_RANGE_PER_SNAPSHOT");setNum(L,"combatFlag",TysUnitStateLayout::UNIT_FLAG_IN_COMBAT);setStr(L,"compressedPolicy","COMPRESSED_UPDATE_IS_DIRTY_SIGNAL_NO_DECOMPRESSION");return 1;}
int dispatchTrack(Lua50::State L){initialize();unsigned long long g=0;if(Lua50::GetTop(L)<2||!resolveGuid(L,2,&g)){Lua50::PushNil(L);Lua50::PushString(L,"BAD_ARGUMENT");return 2;}++g_trackCalls;bool n=false;Entry*e=track(g,&n);if(!e){++g_capacityFailures;Lua50::PushNil(L);Lua50::PushString(L,"TRACK_CAPACITY");return 2;}reconcileEntry(*e);Lua50::PushBool(L,true);Lua50::PushString(L,n?"TRACKED_NEW":"TRACKED_EXISTING");char b[24]={};formatGuid(b,sizeof(b),g);Lua50::PushString(L,b);return 3;}
int dispatchUntrack(Lua50::State L){initialize();unsigned long long g=0;if(Lua50::GetTop(L)<2||!resolveGuid(L,2,&g)){Lua50::PushBool(L,false);Lua50::PushString(L,"BAD_ARGUMENT");return 2;}++g_untrackCalls;Entry*e=find(g);if(!e){Lua50::PushBool(L,false);Lua50::PushString(L,"NOT_TRACKED");return 2;}*e=Entry{};Lua50::PushBool(L,true);Lua50::PushString(L,"UNTRACKED");char b[24]={};formatGuid(b,sizeof(b),g);Lua50::PushString(L,b);return 3;}
int dispatchGet(Lua50::State L){initialize();unsigned long long g=0;if(Lua50::GetTop(L)<2||!resolveGuid(L,2,&g)){Lua50::PushNil(L);Lua50::PushString(L,"BAD_ARGUMENT");return 2;}Entry*e=find(g);if(!e){Lua50::PushNil(L);Lua50::PushString(L,"NOT_TRACKED");return 2;}if(e->dirty)reconcileEntry(*e);return pushEntry(L,*e);}
int dispatchList(Lua50::State L){initialize();Lua50::NewTable(L);int idx=1;for(unsigned i=0;i<MAX_TRACKED;++i){if(!g_entries[i].used)continue;Lua50::PushNumber(L,idx++);pushEntry(L,g_entries[i]);Lua50::SetTable(L,-3);}return 1;}
int dispatchClear(Lua50::State L){initialize();unsigned n=0;for(unsigned i=0;i<MAX_TRACKED;++i)if(g_entries[i].used){g_entries[i]=Entry{};++n;}Lua50::PushNumber(L,n);return 1;}
} // namespace TysUnitStateCore
